/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","eo",{euro:"E?rosigno",lsquo:"Supra 6-citilo",rsquo:"Supra 9-citilo",ldquo:"Supra 66-citilo",rdquo:"Supra 99-citilo",ndash:"Streketo",mdash:"Substreko",iexcl:"Renversita krisigno",cent:"Cendosigno",pound:"Pundosigno",curren:"Monersigno",yen:"Enosigno",brvbar:"Rompita vertikala streko",sect:"Kurba paragrafo",uml:"Tremao",copy:"Kopirajtosigno",ordf:"Adjektiva numerfina?o",laquo:"Duobla malplio-citilo",not:"Negohoko",reg:"Registrita marko",macr:"Superstreko",deg:"Gradosigno",
sup2:"Supra indico 2",sup3:"Supra indico 3",acute:"Dekstra korno",micro:"Mikrosigno",para:"Rekta paragrafo",middot:"Meza punkto",cedil:"Zoeto",sup1:"Supra indico 1",ordm:"Substantiva numerfina?o",raquo:"Duobla plio-citilo",frac14:"Kvaronosigno",frac12:"Duonosigno",frac34:"Trikvaronosigno",iquest:"renversita demandosigno",Agrave:"Latina ?eflitero A kun liva korno",Aacute:"Latina ?eflitero A kun dekstra korno",Acirc:"Latina ?eflitero A kun ?apelo",Atilde:"Latina ?eflitero A kun tildo",Auml:"Latina ?eflitero A kun tremao",
Aring:"Latina ?eflitero A kun superringo",AElig:"Latina ?eflitera ligaturo ?",Ccedil:"Latina ?eflitero C kun zoeto",Egrave:"Latina ?eflitero E kun liva korno",Eacute:"Latina ?eflitero E kun dekstra korno",Ecirc:"Latina ?eflitero E kun ?apelo",Euml:"Latina ?eflitero E kun tremao",Igrave:"Latina ?eflitero I kun liva korno",Iacute:"Latina ?eflitero I kun dekstra korno",Icirc:"Latina ?eflitero I kun ?apelo",Iuml:"Latina ?eflitero I kun tremao",ETH:"Latina ?eflitero islanda edo",Ntilde:"Latina ?eflitero N kun tildo",
Ograve:"Latina ?eflitero O kun liva korno",Oacute:"Latina ?eflitero O kun dekstra korno",Ocirc:"Latina ?eflitero O kun ?apelo",Otilde:"Latina ?eflitero O kun tildo",Ouml:"Latina ?eflitero O kun tremao",times:"Multipliko",Oslash:"Latina ?eflitero O trastrekita",Ugrave:"Latina ?eflitero U kun liva korno",Uacute:"Latina ?eflitero U kun dekstra korno",Ucirc:"Latina ?eflitero U kun ?apelo",Uuml:"Latina ?eflitero U kun tremao",Yacute:"Latina ?eflitero Y kun dekstra korno",THORN:"Latina ?eflitero islanda dorno",
szlig:"Latina etlitero germana sozo (akra s)",agrave:"Latina etlitero a kun liva korno",aacute:"Latina etlitero a kun dekstra korno",acirc:"Latina etlitero a kun ?apelo",atilde:"Latina etlitero a kun tildo",auml:"Latina etlitero a kun tremao",aring:"Latina etlitero a kun superringo",aelig:"Latina etlitera ligaturo ?",ccedil:"Latina etlitero c kun zoeto",egrave:"Latina etlitero e kun liva korno",eacute:"Latina etlitero e kun dekstra korno",ecirc:"Latina etlitero e kun ?apelo",euml:"Latina etlitero e kun tremao",
igrave:"Latina etlitero i kun liva korno",iacute:"Latina etlitero i kun dekstra korno",icirc:"Latina etlitero i kun ?apelo",iuml:"Latina etlitero i kun tremao",eth:"Latina etlitero islanda edo",ntilde:"Latina etlitero n kun tildo",ograve:"Latina etlitero o kun liva korno",oacute:"Latina etlitero o kun dekstra korno",ocirc:"Latina etlitero o kun ?apelo",otilde:"Latina etlitero o kun tildo",ouml:"Latina etlitero o kun tremao",divide:"Dividosigno",oslash:"Latina etlitero o trastrekita",ugrave:"Latina etlitero u kun liva korno",
uacute:"Latina etlitero u kun dekstra korno",ucirc:"Latina etlitero u kun ?apelo",uuml:"Latina etlitero u kun tremao",yacute:"Latina etlitero y kun dekstra korno",thorn:"Latina etlitero islanda dorno",yuml:"Latina etlitero y kun tremao",OElig:"Latina ?eflitera ligaturo ?",oelig:"Latina etlitera ligaturo ?",372:"Latina ?eflitero W kun ?apelo",374:"Latina ?eflitero Y kun ?apelo",373:"Latina etlitero w kun ?apelo",375:"Latina etlitero y kun ?apelo",sbquo:"Suba 9-citilo",8219:"Supra renversita 9-citilo",
bdquo:"Suba 99-citilo",hellip:"Tripunkto",trade:"Varmarka signo",9658:"Nigra sago dekstren",bull:"Bulmarko",rarr:"Sago dekstren",rArr:"Duobla sago dekstren",hArr:"Duobla sago maldekstren",diams:"Nigra kvadrato",asymp:"Preska? egala"});