/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","hu",{euro:"Euró jel",lsquo:"Bal szimpla idéz?jel",rsquo:"Jobb szimpla idéz?jel",ldquo:"Bal dupla idéz?jel",rdquo:"Jobb dupla idéz?jel",ndash:"R?vid gondolatjel",mdash:"Hosszú gondolatjel",iexcl:"Fordított felkiáltójel",cent:"Cent jel",pound:"Font jel",curren:"Valuta jel",yen:"Yen jel",brvbar:"Hosszú kett?spont",sect:"Paragrafus jel",uml:"Kett?s hangzó jel",copy:"Szerz?i jog jel",ordf:"N?i sorrend mutatója",laquo:"Balra mutató duplanyíl",not:"Feltételes k?t?jel",
reg:"Bejegyzett védjegy jele",macr:"Hosszúsági jel",deg:"Fok jel",sup2:"Négyzeten jel",sup3:"K?b?n jel",acute:"éles ékezet",micro:"Mikro-jel",para:"Bekezdés jel",middot:"K?zép pont",cedil:"Cédille",sup1:"Els?n jel",ordm:"Férfi sorrend mutatója",raquo:"Jobbra mutató duplanyíl",frac14:"Egy negyed jel",frac12:"Egy ketted jel",frac34:"Három negyed jel",iquest:"Fordított kérd?jel",Agrave:"Latin nagy A fordított ékezettel",Aacute:"Latin nagy A normál ékezettel",Acirc:"Latin nagy A hajtott ékezettel",Atilde:"Latin nagy A hullámjellel",
Auml:"Latin nagy A kett?spont ékezettel",Aring:"Latin nagy A gy?r? ékezettel",AElig:"Latin nagy ? bet?",Ccedil:"Latin nagy C cedillával",Egrave:"Latin nagy E fordított ékezettel",Eacute:"Latin nagy E normál ékezettel",Ecirc:"Latin nagy E hajtott ékezettel",Euml:"Latin nagy E dupla kett?spont ékezettel",Igrave:"Latin nagy I fordított ékezettel",Iacute:"Latin nagy I normál ékezettel",Icirc:"Latin nagy I hajtott ékezettel",Iuml:"Latin nagy I kett?spont ékezettel",ETH:"Latin nagy Eth bet?",Ntilde:"Latin nagy N hullámjellel",
Ograve:"Latin nagy O fordított ékezettel",Oacute:"Latin nagy O normál ékezettel",Ocirc:"Latin nagy O hajtott ékezettel",Otilde:"Latin nagy O hullámjellel",Ouml:"Latin nagy O kett?spont ékezettel",times:"Szorzás jel",Oslash:"Latin O bet? áthúzással",Ugrave:"Latin nagy U fordított ékezettel",Uacute:"Latin nagy U normál ékezettel",Ucirc:"Latin nagy U hajtott ékezettel",Uuml:"Latin nagy U kett?spont ékezettel",Yacute:"Latin nagy Y normál ékezettel",THORN:"Latin nagy Thorn bet?",szlig:"Latin kis s bet?",
agrave:"Latin kis a fordított ékezettel",aacute:"Latin kis a normál ékezettel",acirc:"Latin kis a hajtott ékezettel",atilde:"Latin kis a hullámjellel",auml:"Latin kis a kett?spont ékezettel",aring:"Latin kis a gy?r? ékezettel",aelig:"Latin kis ? bet?",ccedil:"Latin kis c cedillával",egrave:"Latin kis e fordított ékezettel",eacute:"Latin kis e normál ékezettel",ecirc:"Latin kis e hajtott ékezettel",euml:"Latin kis e dupla kett?spont ékezettel",igrave:"Latin kis i fordított ékezettel",iacute:"Latin kis i normál ékezettel",
icirc:"Latin kis i hajtott ékezettel",iuml:"Latin kis i kett?spont ékezettel",eth:"Latin kis eth bet?",ntilde:"Latin kis n hullámjellel",ograve:"Latin kis o fordított ékezettel",oacute:"Latin kis o normál ékezettel",ocirc:"Latin kis o hajtott ékezettel",otilde:"Latin kis o hullámjellel",ouml:"Latin kis o kett?spont ékezettel",divide:"Osztásjel",oslash:"Latin kis o bet? áthúzással",ugrave:"Latin kis u fordított ékezettel",uacute:"Latin kis u normál ékezettel",ucirc:"Latin kis u hajtott ékezettel",
uuml:"Latin kis u kett?spont ékezettel",yacute:"Latin kis y normál ékezettel",thorn:"Latin kis thorn jel",yuml:"Latin kis y kett?spont ékezettel",OElig:"Latin nagy OE-jel",oelig:"Latin kis oe-jel",372:"Latin nagy W hajtott ékezettel",374:"Latin nagy Y hajtott ékezettel",373:"Latin kis w hajtott ékezettel",375:"Latin kis y hajtott ékezettel",sbquo:"Nyitó nyomdai szimpla idéz?jel",8219:"Záró nyomdai záró idéz?jel",bdquo:"Nyitó nyomdai dupla idéz?jel",hellip:"Három pont",trade:"Kereskedelmi védjegy jele",
9658:"Jobbra mutató fekete mutató",bull:"Golyó",rarr:"Jobbra mutató nyíl",rArr:"Jobbra mutató duplanyíl",hArr:"Bal-jobb duplanyíl",diams:"Fekete gyémánt jel",asymp:"Majdnem egyenl? jel"});