/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","lv",{euro:"Euro zīme",lsquo:"Kreisā  vienkārtīga pēdi?a",rsquo:"Labā  vienkārtīga pēdi?a",ldquo:"Kreisā  dubult pēdi?a",rdquo:"Labā dubult pēdi?a",ndash:"En svītra",mdash:"Em svītra",iexcl:"Apgriezta izsaukuma zīme",cent:"Centu naudas zīme",pound:"Sterli?u mārci?u naudas zīme",curren:"Valūtas zīme",yen:"Jenu naudas zīme",brvbar:"Vertikāla pārrauta līnija",sect:"Paragrāfa zīme",uml:"Diakritiska zīme",copy:"Autortiesību zīme",ordf:"Sievi??as kārtas rādītājs",
laquo:"Kreisā dubult stūra pēdi?u zīme",not:"Neparakstīts",reg:"Re?istrēta zīme",macr:"Garumzīme",deg:"Grādu zīme",sup2:"Aug?raksts divi",sup3:"Aug?raksts trīs",acute:"Akūta uzsvara zīme",micro:"Mikro zīme",para:"Rindkopas zīme ",middot:"Vidējs punkts",cedil:"ā?ītis zem burta",sup1:"Aug?raksts viens",ordm:"Vīri??īgas kārtas rādītājs",raquo:"Labā dubult stūra pēdi?u zīme",frac14:"Vulgāra frakcija 1/4",frac12:"Vulgāra frakcija 1/2",frac34:"Vulgāra frakcija 3/4",iquest:"Apgriezta jautājuma zīme",Agrave:"Lielais latī?u burts A ar uzsvara zīmi",
Aacute:"Lielais  latī?u burts A ar akūtu uzsvara zīmi",Acirc:"Lielais latī?u burts A ar diakritisku zīmi",Atilde:"Lielais latī?u burts A ar tildi ",Auml:"Lielais latī?u burts A ar diakritisko zīmi",Aring:"Lielais latī?u burts A ar aplīti aug?ā",AElig:"Lielais latī?u burts ?",Ccedil:"Lielais latī?u burts C ar ā?īti zem burta",Egrave:"Lielais latī?u burts E ar apostrofu",Eacute:"Lielais latī?u burts E ar akūtu uzsvara zīmi",Ecirc:"Lielais latī?u burts E ar diakritisko zīmi",Euml:"Lielais latī?u burts E ar diakritisko zīmi",
Igrave:"Lielais latī?u burts I ar uzsvaras  zīmi",Iacute:"Lielais latī?u burts I ar akūtu uzsvara zīmi",Icirc:"Lielais latī?u burts I ar diakritisko zīmi",Iuml:"Lielais latī?u burts I ar diakritisko zīmi",ETH:"Lielais latī?u burts Eth",Ntilde:"Lielais latī?u burts N ar tildi",Ograve:"Lielais latī?u burts O ar uzsvara zīmi",Oacute:"Lielais latī?u burts O ar akūto uzsvara zīmi",Ocirc:"Lielais latī?u burts O ar diakritisko zīmi",Otilde:"Lielais latī?u burts O ar tildi",Ouml:"Lielais latī?u burts O ar diakritisko zīmi",
times:"Reizinā?anas zīme ",Oslash:"Lielais latī?u burts O ar iesvītrojumu",Ugrave:"Lielais latī?u burts U ar uzsvaras zīmi",Uacute:"Lielais latī?u burts U ar akūto uzsvars zīmi",Ucirc:"Lielais latī?u burts U ar diakritisko zīmi",Uuml:"Lielais latī?u burts U ar diakritisko zīmi",Yacute:"Lielais latī?u burts Y ar akūto uzsvaras zīmi",THORN:"Lielais latī?u burts torn",szlig:"Mazs latī?u burts ar ligatūru",agrave:"Mazs latī?u burts a ar uzsvara zīmi",aacute:"Mazs latī?u burts a ar akūto uzsvara zīmi",
acirc:"Mazs latī?u burts a ar diakritisko zīmi",atilde:"Mazs latī?u burts a ar tildi",auml:"Mazs latī?u burts a ar diakritisko zīmi",aring:"Mazs latī?u burts a ar aplīti aug?ā",aelig:"Mazs latī?u burts ?",ccedil:"Mazs latī?u burts c ar ā?īti zem burta",egrave:"Mazs latī?u burts e ar uzsvara zīmi ",eacute:"Mazs latī?u burts e ar akūtu uzsvara zīmi",ecirc:"Mazs latī?u burts e ar diakritisko zīmi",euml:"Mazs latī?u burts e ar diakritisko zīmi",igrave:"Mazs latī?u burts i ar uzsvara zīmi ",iacute:"Mazs latī?u burts i ar akūtu uzsvara zīmi",
icirc:"Mazs latī?u burts i ar diakritisko zīmi",iuml:"Mazs latī?u burts i ar diakritisko zīmi",eth:"Mazs latī?u burts eth",ntilde:"Mazs latī?u burts n ar tildi",ograve:"Mazs latī?u burts o ar uzsvara zīmi ",oacute:"Mazs latī?u burts o ar akūtu uzsvara zīmi",ocirc:"Mazs latī?u burts o ar diakritisko zīmi",otilde:"Mazs latī?u burts o ar tildi",ouml:"Mazs latī?u burts o ar diakritisko zīmi",divide:"Dalī?anas zīme",oslash:"Mazs latī?u burts o ar iesvītrojumu",ugrave:"Mazs latī?u burts u ar uzsvara zīmi ",
uacute:"Mazs latī?u burts u ar  akūtu uzsvara zīmi",ucirc:"Mazs latī?u burts u ar diakritisko zīmi",uuml:"Mazs latī?u burts u ar diakritisko zīmi",yacute:"Mazs latī?u burts y ar  akūtu uzsvaras zīmi",thorn:"Mazs latī?u burts torns",yuml:"Mazs latī?u burts y ar diakritisko zīmi",OElig:"Liela latī?u ligatūra OE",oelig:"Maza latī?u ligatūra oe",372:"Liels latī?u burts W ar diakritisko zīmi ",374:"Liels latī?u burts Y ar diakritisko zīmi ",373:"Mazs latī?u burts w ar diakritisko zīmi ",375:"Mazs latī?u burts y ar diakritisko zīmi ",
sbquo:"Mazas-9 vienkārtīgas pēdi?as",8219:"Lielas-9 vienkārtīgas apgrieztas pēdi?as",bdquo:"Mazas-9 dubultas pēdi?as",hellip:"Horizontāli daudzpunkti",trade:"Pre?u zīmes zīme",9658:"Melns pa labi pagriezts radītājs",bull:"Lode",rarr:"Bulta pa labi",rArr:"Dubulta Bulta pa labi",hArr:"Bulta pa kreisi",diams:"Dubulta Bulta pa kreisi",asymp:"Gandrīz vienāds ar"});