/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pl",{euro:"Znak euro",lsquo:"Cudzys?ów pojedynczy otwieraj?cy",rsquo:"Cudzys?ów pojedynczy zamykaj?cy",ldquo:"Cudzys?ów apostrofowy otwieraj?cy",rdquo:"Cudzys?ów apostrofowy zamykaj?cy",ndash:"Pó?pauza",mdash:"Pauza",iexcl:"Odwrócony wykrzyknik",cent:"Znak centa",pound:"Znak funta",curren:"Znak waluty",yen:"Znak jena",brvbar:"Przerwana pionowa kreska",sect:"Paragraf",uml:"Diereza",copy:"Znak praw autorskich",ordf:"Wska?nik rodzaju ?eńskiego liczebnika porz?dkowego",
laquo:"Lewy cudzys?ów ostrok?tny",not:"Znak negacji",reg:"Zastrze?ony znak towarowy",macr:"Makron",deg:"Znak stopnia",sup2:"Druga pot?ga",sup3:"Trzecia pot?ga",acute:"Akcent ostry",micro:"Znak mikro",para:"Znak akapitu",middot:"Kropka ?rodkowa",cedil:"Cedylla",sup1:"Pierwsza pot?ga",ordm:"Wska?nik rodzaju m?skiego liczebnika porz?dkowego",raquo:"Prawy cudzys?ów ostrok?tny",frac14:"U?amek zwyk?y jedna czwarta",frac12:"U?amek zwyk?y jedna druga",frac34:"U?amek zwyk?y trzy czwarte",iquest:"Odwrócony znak zapytania",
Agrave:"Wielka litera A z akcentem ci??kim",Aacute:"Wielka litera A z akcentem ostrym",Acirc:"Wielka litera A z akcentem przeci?g?ym",Atilde:"Wielka litera A z tyld?",Auml:"Wielka litera A z dierez?",Aring:"Wielka litera A z kó?kiem",AElig:"Wielka ligatura ?",Ccedil:"Wielka litera C z cedyll?",Egrave:"Wielka litera E z akcentem ci??kim",Eacute:"Wielka litera E z akcentem ostrym",Ecirc:"Wielka litera E z akcentem przeci?g?ym",Euml:"Wielka litera E z dierez?",Igrave:"Wielka litera I z akcentem ci??kim",
Iacute:"Wielka litera I z akcentem ostrym",Icirc:"Wielka litera I z akcentem przeci?g?ym",Iuml:"Wielka litera I z dierez?",ETH:"Wielka litera Eth",Ntilde:"Wielka litera N z tyld?",Ograve:"Wielka litera O z akcentem ci??kim",Oacute:"Wielka litera O z akcentem ostrym",Ocirc:"Wielka litera O z akcentem przeci?g?ym",Otilde:"Wielka litera O z tyld?",Ouml:"Wielka litera O z dierez?",times:"Znak mno?enia wektorowego",Oslash:"Wielka litera O z przekre?leniem",Ugrave:"Wielka litera U z akcentem ci??kim",Uacute:"Wielka litera U z akcentem ostrym",
Ucirc:"Wielka litera U z akcentem przeci?g?ym",Uuml:"Wielka litera U z dierez?",Yacute:"Wielka litera Y z akcentem ostrym",THORN:"Wielka litera Thorn",szlig:"Ma?a litera ostre s (eszet)",agrave:"Ma?a litera a z akcentem ci??kim",aacute:"Ma?a litera a z akcentem ostrym",acirc:"Ma?a litera a z akcentem przeci?g?ym",atilde:"Ma?a litera a z tyld?",auml:"Ma?a litera a z dierez?",aring:"Ma?a litera a z kó?kiem",aelig:"Ma?a ligatura ?",ccedil:"Ma?a litera c z cedyll?",egrave:"Ma?a litera e z akcentem ci??kim",
eacute:"Ma?a litera e z akcentem ostrym",ecirc:"Ma?a litera e z akcentem przeci?g?ym",euml:"Ma?a litera e z dierez?",igrave:"Ma?a litera i z akcentem ci??kim",iacute:"Ma?a litera i z akcentem ostrym",icirc:"Ma?a litera i z akcentem przeci?g?ym",iuml:"Ma?a litera i z dierez?",eth:"Ma?a litera eth",ntilde:"Ma?a litera n z tyld?",ograve:"Ma?a litera o z akcentem ci??kim",oacute:"Ma?a litera o z akcentem ostrym",ocirc:"Ma?a litera o z akcentem przeci?g?ym",otilde:"Ma?a litera o z tyld?",ouml:"Ma?a litera o z dierez?",
divide:"Anglosaski znak dzielenia",oslash:"Ma?a litera o z przekre?leniem",ugrave:"Ma?a litera u z akcentem ci??kim",uacute:"Ma?a litera u z akcentem ostrym",ucirc:"Ma?a litera u z akcentem przeci?g?ym",uuml:"Ma?a litera u z dierez?",yacute:"Ma?a litera y z akcentem ostrym",thorn:"Ma?a litera thorn",yuml:"Ma?a litera y z dierez?",OElig:"Wielka ligatura OE",oelig:"Ma?a ligatura oe",372:"Wielka litera W z akcentem przeci?g?ym",374:"Wielka litera Y z akcentem przeci?g?ym",373:"Ma?a litera w z akcentem przeci?g?ym",
375:"Ma?a litera y z akcentem przeci?g?ym",sbquo:"Pojedynczy apostrof dolny",8219:"Pojedynczy apostrof górny",bdquo:"Podwójny apostrof dolny",hellip:"Wielokropek",trade:"Znak towarowy",9658:"Czarny wska?nik wskazuj?cy w prawo",bull:"Punktor",rarr:"Strza?ka w prawo",rArr:"Podwójna strza?ka w prawo",hArr:"Podwójna strza?ka w lewo",diams:"Czarny znak karo",asymp:"Znak prawie równe"});