/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sk",{euro:"Znak eura",lsquo:"?avá jednoduchá úvodzovka",rsquo:"Pravá jednoduchá úvodzovka",ldquo:"Pravá dvojitá úvodzovka",rdquo:"Pravá dvojitá úvodzovka",ndash:"En poml?ka",mdash:"Em poml?ka",iexcl:"Obráteny vykri?ník",cent:"Znak centu",pound:"Znak libry",curren:"Znak meny",yen:"Znak jenu",brvbar:"Preru?ená zvislá ?iara",sect:"Znak odseku",uml:"Prehláska",copy:"Znak copyrightu",ordf:"?ensky indikátor rodu",laquo:"Znak dvojitych lomenych úvodzoviek v?avo",not:"Logisticky zápor",
reg:"Znak registrácie",macr:"Poml?ka nad",deg:"Znak stupňa",sup2:"Dvojka ako horny index",sup3:"Trojka ako horny index",acute:"D??eň",micro:"Znak mikro",para:"Znak odstavca",middot:"Bodka uprostred",cedil:"Chvost v?avo",sup1:"Jednotka ako horny index",ordm:"Mu?sky indikátor rodu",raquo:"Znak dvojitych lomenych úvodzoviek vpravo",frac14:"Oby?ajny zlomok jedna ?tvrtina",frac12:"Oby?ajny zlomok jedna polovica",frac34:"Oby?ajny zlomok tri ?tvrtiny",iquest:"Oto?eny otáznik",Agrave:"Ve?ké písmeno latinky A s accentom",
Aacute:"Ve?ké písmeno latinky A s d??ňom",Acirc:"Ve?ké písmeno latinky A s m?k?eňom",Atilde:"Ve?ké písmeno latinky A s tildou",Auml:"Ve?ké písmeno latinky A s dvoma bodkami",Aring:"Ve?ké písmeno latinky A s krú?kom nad",AElig:"Ve?ké písmeno latinky ?",Ccedil:"Ve?ké písmeno latinky C s chvostom v?avo",Egrave:"Ve?ké písmeno latinky E s accentom",Eacute:"Ve?ké písmeno latinky E s d??ňom",Ecirc:"Ve?ké písmeno latinky E s m?k?eňom",Euml:"Ve?ké písmeno latinky E s dvoma bodkami",Igrave:"Ve?ké písmeno latinky I s accentom",
Iacute:"Ve?ké písmeno latinky I s d??ňom",Icirc:"Ve?ké písmeno latinky I s m?k?eňom",Iuml:"Ve?ké písmeno latinky I s dvoma bodkami",ETH:"Ve?ké písmeno latinky Eth",Ntilde:"Ve?ké písmeno latinky N s tildou",Ograve:"Ve?ké písmeno latinky O s accentom",Oacute:"Ve?ké písmeno latinky O s d??ňom",Ocirc:"Ve?ké písmeno latinky O s m?k?eňom",Otilde:"Ve?ké písmeno latinky O s tildou",Ouml:"Ve?ké písmeno latinky O s dvoma bodkami",times:"Znak násobenia",Oslash:"Ve?ké písmeno latinky O pre?krtnuté",Ugrave:"Ve?ké písmeno latinky U s accentom",
Uacute:"Ve?ké písmeno latinky U s d??ňom",Ucirc:"Ve?ké písmeno latinky U s m?k?eňom",Uuml:"Ve?ké písmeno latinky U s dvoma bodkami",Yacute:"Ve?ké písmeno latinky Y s d??ňom",THORN:"Ve?ké písmeno latinky Thorn",szlig:"Malé písmeno latinky ostré s",agrave:"Malé písmeno latinky a s accentom",aacute:"Malé písmeno latinky a s d??ňom",acirc:"Malé písmeno latinky a s m?k?eňom",atilde:"Malé písmeno latinky a s tildou",auml:"Malé písmeno latinky a s dvoma bodkami",aring:"Malé písmeno latinky a s krú?kom nad",
aelig:"Malé písmeno latinky ?",ccedil:"Malé písmeno latinky c s chvostom v?avo",egrave:"Malé písmeno latinky e s accentom",eacute:"Malé písmeno latinky e s d??ňom",ecirc:"Malé písmeno latinky e s m?k?eňom",euml:"Malé písmeno latinky e s dvoma bodkami",igrave:"Malé písmeno latinky i s accentom",iacute:"Malé písmeno latinky i s d??ňom",icirc:"Malé písmeno latinky i s m?k?eňom",iuml:"Malé písmeno latinky i s dvoma bodkami",eth:"Malé písmeno latinky eth",ntilde:"Malé písmeno latinky n s tildou",ograve:"Malé písmeno latinky o s accentom",
oacute:"Malé písmeno latinky o s d??ňom",ocirc:"Malé písmeno latinky o s m?k?eňom",otilde:"Malé písmeno latinky o s tildou",ouml:"Malé písmeno latinky o s dvoma bodkami",divide:"Znak delenia",oslash:"Malé písmeno latinky o pre?krtnuté",ugrave:"Malé písmeno latinky u s accentom",uacute:"Malé písmeno latinky u s d??ňom",ucirc:"Malé písmeno latinky u s m?k?eňom",uuml:"Malé písmeno latinky u s dvoma bodkami",yacute:"Malé písmeno latinky y s d??ňom",thorn:"Malé písmeno latinky thorn",yuml:"Malé písmeno latinky y s dvoma bodkami",
OElig:"Ve?ká ligatúra latinky OE",oelig:"Malá ligatúra latinky OE",372:"Ve?ké písmeno latinky W s m?k?eňom",374:"Ve?ké písmeno latinky Y s m?k?eňom",373:"Malé písmeno latinky w s m?k?eňom",375:"Malé písmeno latinky y s m?k?eňom",sbquo:"Dolná jednoduchá 9-úvodzovka",8219:"Horná jednoduchá oto?ená 9-úvodzovka",bdquo:"Dolná dvojitá 9-úvodzovka",hellip:"Trojbodkovy úvod",trade:"Znak ibchodnej zna?ky",9658:"?ierny ukazovate? smerujúci vpravo",bull:"Kruh",rarr:"?ípka vpravo",rArr:"Dvojitá ?ipka vpravo",
hArr:"Dvojitá ?ipka v?avo a vpravo",diams:"?ierne piky",asymp:"Skoro sa rovná"});