/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sl",{euro:"Evro znak",lsquo:"Levi enojni narekovaj",rsquo:"Desni enojni narekovaj",ldquo:"Levi dvojni narekovaj",rdquo:"Desni dvojni narekovaj",ndash:"En pomi?ljaj",mdash:"Em pomi?ljaj",iexcl:"Obrnjen klicaj",cent:"Cent znak",pound:"Funt znak",curren:"Znak valute",yen:"Jen znak",brvbar:"Zlomljena ?rta",sect:"Znak oddelka",uml:"Diaeresis",copy:"Znak avtorskih pravic",ordf:"?enski zaporedni kazalnik",laquo:"Levi obrnjen dvojni kotni narekovaj",not:"Ne znak",reg:"Registrirani znak",
macr:"Macron",deg:"Znak stopinj",sup2:"Nadpisano dva",sup3:"Nadpisano tri",acute:"Ostrivec",micro:"Mikro znak",para:"Pilcrow znak",middot:"Sredinska pika",cedil:"Cedilla",sup1:"Nadpisano ena",ordm:"Mo?ki zaporedni kazalnik",raquo:"Desno obrnjen dvojni kotni narekovaj",frac14:"Ena ?etrtina",frac12:"Ena polovica",frac34:"Tri ?etrtine",iquest:"Obrnjen vpra?aj",Agrave:"Velika latinska ?rka A s krativcem",Aacute:"Velika latinska ?rka A z ostrivcem",Acirc:"Velika latinska ?rka A s stre?ico",Atilde:"Velika latinska ?rka A z tildo",
Auml:"Velika latinska ?rka A z diaeresis-om",Aring:"Velika latinska ?rka A z obro?em",AElig:"Velika latinska ?rka ?",Ccedil:"Velika latinska ?rka C s cedillo",Egrave:"Velika latinska ?rka E s krativcem",Eacute:"Velika latinska ?rka E z ostrivcem",Ecirc:"Velika latinska ?rka E s stre?ico",Euml:"Velika latinska ?rka E z diaeresis-om",Igrave:"Velika latinska ?rka I s krativcem",Iacute:"Velika latinska ?rka I z ostrivcem",Icirc:"Velika latinska ?rka I s stre?ico",Iuml:"Velika latinska ?rka I z diaeresis-om",
ETH:"Velika latinska ?rka Eth",Ntilde:"Velika latinska ?rka N s tildo",Ograve:"Velika latinska ?rka O s krativcem",Oacute:"Velika latinska ?rka O z ostrivcem",Ocirc:"Velika latinska ?rka O s stre?ico",Otilde:"Velika latinska ?rka O s tildo",Ouml:"Velika latinska ?rka O z diaeresis-om",times:"Znak za mno?enje",Oslash:"Velika pre?rtana latinska ?rka O",Ugrave:"Velika latinska ?rka U s krativcem",Uacute:"Velika latinska ?rka U z ostrivcem",Ucirc:"Velika latinska ?rka U s stre?ico",Uuml:"Velika latinska ?rka U z diaeresis-om",
Yacute:"Velika latinska ?rka Y z ostrivcem",THORN:"Velika latinska ?rka Thorn",szlig:"Mala ostra latinska ?rka s",agrave:"Mala latinska ?rka a s krativcem",aacute:"Mala latinska ?rka a z ostrivcem",acirc:"Mala latinska ?rka a s stre?ico",atilde:"Mala latinska ?rka a s tildo",auml:"Mala latinska ?rka a z diaeresis-om",aring:"Mala latinska ?rka a z obro?em",aelig:"Mala latinska ?rka ?",ccedil:"Mala latinska ?rka c s cedillo",egrave:"Mala latinska ?rka e s krativcem",eacute:"Mala latinska ?rka e z ostrivcem",
ecirc:"Mala latinska ?rka e s stre?ico",euml:"Mala latinska ?rka e z diaeresis-om",igrave:"Mala latinska ?rka i s krativcem",iacute:"Mala latinska ?rka i z ostrivcem",icirc:"Mala latinska ?rka i s stre?ico",iuml:"Mala latinska ?rka i z diaeresis-om",eth:"Mala latinska ?rka eth",ntilde:"Mala latinska ?rka n s tildo",ograve:"Mala latinska ?rka o s krativcem",oacute:"Mala latinska ?rka o z ostrivcem",ocirc:"Mala latinska ?rka o s stre?ico",otilde:"Mala latinska ?rka o s tildo",ouml:"Mala latinska ?rka o z diaeresis-om",
divide:"Znak za deljenje",oslash:"Mala pre?rtana latinska ?rka o",ugrave:"Mala latinska ?rka u s krativcem",uacute:"Mala latinska ?rka u z ostrivcem",ucirc:"Mala latinska ?rka u s stre?ico",uuml:"Mala latinska ?rka u z diaeresis-om",yacute:"Mala latinska ?rka y z ostrivcem",thorn:"Mala latinska ?rka thorn",yuml:"Mala latinska ?rka y z diaeresis-om",OElig:"Velika latinska ligatura OE",oelig:"Mala latinska ligatura oe",372:"Velika latinska ?rka W s stre?ico",374:"Velika latinska ?rka Y s stre?ico",
373:"Mala latinska ?rka w s stre?ico",375:"Mala latinska ?rka y s stre?ico",sbquo:"Enojni nizki-9 narekovaj",8219:"Enojni visoki-obrnjen-9 narekovaj",bdquo:"Dvojni nizki-9 narekovaj",hellip:"Horizontalni izpust",trade:"Znak blagovne znamke",9658:"?rni desno-usmerjen kazalec",bull:"Krogla",rarr:"Desno-usmerjena pu??ica",rArr:"Desno-usmerjena dvojna pu??ica",hArr:"Leva in desna dvojna pu??ica",diams:"?rna kara",asymp:"Skoraj enako"});