/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","tr",{euro:"Euro i?areti",lsquo:"Sol tek t?rnak i?areti",rsquo:"Sa? tek t?rnak i?areti",ldquo:"Sol ?ift t?rnak i?areti",rdquo:"Sa? ?ift t?rnak i?areti",ndash:"En tire",mdash:"Em tire",iexcl:"Ters ünlem i?areti",cent:"Cent i?areti",pound:"Pound i?areti",curren:"Para birimi i?areti",yen:"Yen i?areti",brvbar:"K?r?k bar",sect:"B?lüm i?areti",uml:"?ki sesli harfin ayr?lmas?",copy:"Telif hakk? i?areti",ordf:"Di?il s?ral? g?sterge",laquo:"Sol-i?aret ?ift a?? t?rnak i?areti",
not:"Not i?areti",reg:"Kay?tl? i?areti",macr:"Makron",deg:"Derece i?areti",sup2:"?kili üstsimge",sup3:"ü?lü üstsimge",acute:"Aksan i?areti",micro:"Mikro i?areti",para:"Pilcrow i?areti",middot:"Orta nokta",cedil:"Kedilla",sup1:"üstsimge",ordm:"Eril s?ral? g?sterge",raquo:"Sa? i?aret ?ift a?? t?rnak i?areti",frac14:"Baya?? kesrin d?rtte biri",frac12:"Baya?? kesrin bir yar?m",frac34:"Baya?? kesrin d?rtte ü?",iquest:"Ters soru i?areti",Agrave:"Aksanl? latin harfi",Aacute:"A??r? aksan?yla Latin harfi",
Acirc:"?arp?k Latin harfi",Atilde:"Tilde latin harfi",Auml:"Sesli harf ayr?l?ml?? latin harfi",Aring:"Halkal? latin büyük A harfi",AElig:"Latin büyük ? harfi",Ccedil:"Latin büyük C harfi ile kedilla",Egrave:"Aksanl? latin büyük E harfi",Eacute:"A??r? vurgulu latin büyük E harfi",Ecirc:"?arp?k latin büyük E harfi",Euml:"Sesli harf ayr?l?ml?? latin büyük E harfi",Igrave:"Aksanl? latin büyük I harfi",Iacute:"A??r? aksanl? latin büyük I harfi",Icirc:"?arp?k latin büyük I harfi",Iuml:"Sesli harf ayr?l?ml?? latin büyük I harfi",
ETH:"Latin büyük Eth harfi",Ntilde:"Tildeli latin büyük N harfi",Ograve:"Aksanl? latin büyük O harfi",Oacute:"A??r? aksanl? latin büyük O harfi",Ocirc:"?arp?k latin büyük O harfi",Otilde:"Tildeli latin büyük O harfi",Ouml:"Sesli harf ayr?l?ml? latin büyük O harfi",times:"?arpma i?areti",Oslash:"Vurgulu latin büyük O harfi",Ugrave:"Aksanl? latin büyük U harfi",Uacute:"A??r? aksanl? latin büyük U harfi",Ucirc:"?arp?k latin büyük U harfi",Uuml:"Sesli harf ayr?l?ml? latin büyük U harfi",Yacute:"A??r? aksanl? latin büyük Y harfi",
THORN:"Latin büyük Thorn harfi",szlig:"Latin kü?ük keskin s harfi",agrave:"Aksanl? latin kü?ük a harfi",aacute:"A??r? aksanl? latin kü?ük a harfi",acirc:"?arp?k latin kü?ük a harfi",atilde:"Tildeli latin kü?ük a harfi",auml:"Sesli harf ayr?l?ml? latin kü?ük a harfi",aring:"Halkal? latin kü?ük a harfi",aelig:"Latin büyük ? harfi",ccedil:"Kedillal? latin kü?ük c harfi",egrave:"Aksanl? latin kü?ük e harfi",eacute:"A??r? aksanl? latin kü?ük e harfi",ecirc:"?arp?k latin kü?ük e harfi",euml:"Sesli harf ayr?l?ml? latin kü?ük e harfi",
igrave:"Aksanl? latin kü?ük i harfi",iacute:"A??r? aksanl? latin kü?ük i harfi",icirc:"?arp?k latin kü?ük i harfi",iuml:"Sesli harf ayr?l?ml? latin kü?ük i harfi",eth:"Latin kü?ük eth harfi",ntilde:"Tildeli latin kü?ük n harfi",ograve:"Aksanl? latin kü?ük o harfi",oacute:"A??r? aksanl? latin kü?ük o harfi",ocirc:"?arp?k latin kü?ük o harfi",otilde:"Tildeli latin kü?ük o harfi",ouml:"Sesli harf ayr?l?ml? latin kü?ük o harfi",divide:"B?lme i?areti",oslash:"Vurgulu latin kü?ük o harfi",ugrave:"Aksanl? latin kü?ük u harfi",
uacute:"A??r? aksanl? latin kü?ük u harfi",ucirc:"?arp?k latin kü?ük u harfi",uuml:"Sesli harf ayr?l?ml? latin kü?ük u harfi",yacute:"A??r? aksanl? latin kü?ük y harfi",thorn:"Latin kü?ük thorn harfi",yuml:"Sesli harf ayr?l?ml? latin kü?ük y harfi",OElig:"Latin büyük ba?l? OE harfi",oelig:"Latin kü?ük ba?l? oe harfi",372:"?arp?k latin büyük W harfi",374:"?arp?k latin büyük Y harfi",373:"?arp?k latin kü?ük w harfi",375:"?arp?k latin kü?ük y harfi",sbquo:"Tek dü?ük-9 t?rnak i?areti",8219:"Tek yüksek-ters-9 t?rnak i?areti",
bdquo:"?ift dü?ük-9 t?rnak i?areti",hellip:"Yatay elips",trade:"Marka tescili i?areti",9658:"Siyah sa? i?aret i?aret?isi",bull:"Koyu nokta",rarr:"Sa?a do?ru ok",rArr:"Sa?a do?ru ?ift ok",hArr:"Sol, sa? ?ift ok",diams:"Siyah elmas tak?m?",asymp:"Hemen hemen e?it"});