/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","cs",{title:"Instrukce pro p?ístupnost",contents:"Obsah nápovědy. Pro uzav?ení tohoto dialogu stiskněte klávesu ESC.",legend:[{name:"Obecné",items:[{name:"Panel nástroj? editoru",legend:"Stiskněte${toolbarFocus} k procházení panelu nástroj?. P?ejděte na dal?í a p?edchozí skupiny pomocí TAB a SHIFT-TAB. P?echod na dal?í a p?edchozí tla?ítko panelu nástroj? je pomocí ?IPKA VPRAVO nebo ?IPKA VLEVO. Stisknutím mezerníku nebo klávesy ENTER tla?ítko aktivujete."},{name:"Dialogové okno editoru",
legend:"Uvnit? dialogového okna stiskněte TAB pro p?esunutí na dal?í pole, stiskněte SHIFT + TAB pro p?esun na p?edchozí pole, stiskněte ENTER pro odeslání dialogu, stiskněte ESC pro jeho zru?ení. Pro dialogová okna, která mají mnoho karet stiskněte ALT + F10 pr oprocházení seznamu karet. Pak se p?esuňte na dal?í kartu pomocí TAB nebo ?IPKA VPRAVO. Pro p?esun na p?edchozí stiskněte SHIFT + TAB nebo ?IPKA VLEVO. Stiskněte MEZERNíK nebo ENTER pro vybrání stránky karet."},{name:"Kontextové menu editoru",
legend:"Stiskněte ${contextMenu} nebo klávesu APPLICATION k otev?ení kontextového menu. Pak se p?esuňte na dal?í mo?nost menu pomocí TAB nebo ?IPKY DOL?. P?esuňte se na p?edchozí mo?nost pomocí  SHIFT+TAB nebo ?IPKY NAHORU. Stiskněte MEZERNíK nebo ENTER pro zvolení mo?nosti menu. Podmenu sou?asné mo?nosti otev?ete pomocí MEZERNíKU nebo ENTER ?i ?IPKY DOLEVA. Kontextové menu uzav?ete stiskem ESC."},{name:"Ráme?ek seznamu editoru",legend:"Uvnit? ráme?ku seznamu se p?esunete na dal?í polo?ku menu pomocí TAB nebo ?IPKA DOL?. Na p?edchozí polo?ku se p?esunete SHIFT + TAB nebo ?IPKA NAHORU. Stiskněte MEZERNíK nebo ENTER pro zvolení mo?nosti seznamu. Stiskněte ESC pro uzav?ení seznamu."},
{name:"Li?ta cesty prvku v editoru",legend:"Stiskněte ${elementsPathFocus} pro procházení li?ty cesty prvku. Na dal?í tla?ítko prvku se p?esunete pomocí TAB nebo ?IPKA VPRAVO. Na p?edchozí polo?ku se p?esunete pomocí SHIFT + TAB nebo ?IPKA VLEVO. Stiskněte MEZERNíK nebo ENTER pro vybrání prvku v editoru."}]},{name:"P?íkazy",items:[{name:" P?íkaz Zpět",legend:"Stiskněte ${undo}"},{name:" P?íkaz Znovu",legend:"Stiskněte ${redo}"},{name:" P?íkaz Tu?né",legend:"Stiskněte ${bold}"},{name:" P?íkaz Kurzíva",
legend:"Stiskněte ${italic}"},{name:" P?íkaz Podtr?ení",legend:"Stiskněte ${underline}"},{name:" P?íkaz Odkaz",legend:"Stiskněte ${link}"},{name:" P?íkaz Skryt panel nástroj?",legend:"Stiskněte ${toolbarCollapse}"},{name:"P?íkaz pro p?ístup k p?edchozímu prostoru zamě?ení",legend:"Stiskněte ${accessPreviousSpace} pro p?ístup k nejbli??ímu nedosa?itelnému prostoru zamě?ení p?ed st?í?kou, nap?íklad: dva p?ilehlé prvky HR. Pro dosa?ení vzdálenych prostor? zamě?ení tuto kombinaci kláves opakujte."},{name:"P?íkaz pro p?ístup k dal?ímu prostoru zamě?ení",
legend:"Stiskněte ${accessNextSpace} pro p?ístup k nejbli??ímu nedosa?itelnému prostoru zamě?ení po st?í?ce, nap?íklad: dva p?ilehlé prvky HR. Pro dosa?ení vzdálenych prostor? zamě?ení tuto kombinaci kláves opakujte."},{name:" Nápověda p?ístupnosti",legend:"Stiskněte ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tabulátor",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pauza",capslock:"Caps lock",escape:"Escape",pageUp:"Stránka nahoru",pageDown:"Stránka dol?",end:"Konec",home:"Dom?",leftArrow:"?ipka vlevo",
upArrow:"?ipka nahoru",rightArrow:"?ipka vpravo",downArrow:"?ipka dol?",insert:"Vlo?it","delete":"Smazat",leftWindowKey:"Levá klávesa Windows",rightWindowKey:"Pravá klávesa Windows",selectKey:"Vyberte klávesu",numpad0:"Numerická klávesa 0",numpad1:"Numerická klávesa 1",numpad2:"Numerická klávesa 2",numpad3:"Numerická klávesa 3",numpad4:"Numerická klávesa 4",numpad5:"Numerická klávesa 5",numpad6:"Numerická klávesa 6",numpad7:"Numerická klávesa 7",numpad8:"Numerická klávesa 8",numpad9:"Numerická klávesa 9",
multiply:"Numerická klávesa násobení",add:"P?idat",subtract:"Numerická klávesa ode?ítání",decimalPoint:"Desetinná te?ka",divide:"Numerická klávesa dělení",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num lock",scrollLock:"Scroll lock",semiColon:"St?edník",equalSign:"Rovnítko",comma:"?árka",dash:"Poml?ka",period:"Te?ka",forwardSlash:"Lomítko",graveAccent:"P?ízvuk",openBracket:"Otev?ená hranatá závorka",backSlash:"Obrácené lomítko",closeBracket:"Uzav?ená hranatá závorka",
singleQuote:"Jednoduchá uvozovka"});