/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","eo",{title:"Uzindikoj pri atingeblo",contents:"Helpilenhavo. Por fermi tiun dialogon, premu la ESKAPAN klavon.",legend:[{name:"?enerala?oj",items:[{name:"Ilbreto de la redaktilo",legend:"Premu ${toolbarFocus} por atingi la ilbreton. Movi?u al la sekva a? anta?a grupoj de la ilbreto per la klavoj TABA kaj MAJUSKLIGA-TABA. Movi?u al la sekva a? anta?a butonoj de la ilbreto per la klavoj SAGO DEKSTREN kaj SAGO MALDEKSTREN. Premu la SPACETklavon a? la ENENklavon por aktivigi la ilbretbutonon."},
{name:"Redaktildialogo",legend:"En dialogo, premu la TABAN klavon por navigi al la sekva dialogkampo, premu la MAJUSKLIGAN + TABAN klavojn por reveni al la anta?a kampo, premu la ENENklavon por sendi la dialogon, premu la ESKAPAN klavon por nuligi la dialogon. Por dialogoj kun pluraj retpa?oj sub langetoj, premu ALT + F10 por navigi al la langetlisto. Poste movi?u al la sekva langeto per la klavo TABA a? SAGO DEKSTREN. Movi?u al la anta?a langeto per la klavoj MAJUSKLIGA + TABA a?  SAGO MALDEKSTREN. Premu la SPACETklavon a? la ENENklavon por selekti la langetretpa?on."},
{name:"Kunteksta menuo de la redaktilo",legend:"Premu ${contextMenu} a? entajpu la KLAVKOMBINA?ON por malfermi la kuntekstan menuon. Poste movi?u al la sekva opcio de la menuo per la klavoj TABA a? SAGO SUBEN. Movi?u al la anta?a opcio per la klavoj MAJUSKLGA + TABA a? SAGO SUPREN. Premu la SPACETklavon a? ENENklavon por selekti la menuopcion. Malfermu la submenuon de la kuranta opcio per la SPACETklavo a? la ENENklavo a? la SAGO DEKSTREN. Revenu al la elemento de la patra menuo per la klavoj ESKAPA a? SAGO MALDEKSTREN. Fermu la kuntekstan menuon per la ESKAPA klavo."},
{name:"Fallisto de la redaktilo",legend:"En fallisto, movi?u al la sekva listelemento per la klavoj TABA a? SAGO SUBEN. Movi?u al la anta?a listelemento per la klavoj MAJUSKLIGA + TABA a? SAGO SUPREN. Premu la SPACETklavon a? ENENklavon por selekti la opcion en la listo. Premu la ESKAPAN klavon por fermi la falmenuon."},{name:"Breto indikanta la vojon al la redaktilelementoj",legend:"Premu ${elementsPathFocus} por navigi al la breto indikanta la vojon al la redaktilelementoj. Movi?u al la butono de la sekva elemento per la klavoj TABA a? SAGO DEKSTREN. Movi?u al la butono de la anta?a elemento per la klavoj MAJUSKLIGA + TABA a? SAGO MALDEKSTREN. Premu la SPACETklavon a? ENENklavon por selekti la elementon en la redaktilo."}]},
{name:"Komandoj",items:[{name:"Komando malfari",legend:"Premu ${undo}"},{name:"Komando refari",legend:"Premu ${redo}"},{name:"Komando grasa",legend:"Premu ${bold}"},{name:"Komando kursiva",legend:"Premu ${italic}"},{name:"Komando substreki",legend:"Premu ${underline}"},{name:"Komando ligilo",legend:"Premu ${link}"},{name:"Komando faldi la ilbreton",legend:"Premu ${toolbarCollapse}"},{name:"Komando por atingi la anta?an fokusan spacon",legend:"Press ${accessPreviousSpace} por atingi la plej proksiman neatingeblan fokusan spacon anta? la kursoro, ekzemple : du kuntu?i?ajn HR elementojn. Ripetu la klavkombina?on por atingi malproksimajn fokusajn spacojn."},
{name:"Komando por atingi la sekvan fokusan spacon",legend:"Press ${accessNextSpace} por atingi la plej proksiman neatingeblan fokusan spacon post la kursoro, ekzemple : du kuntu?i?ajn HR elementojn. Ripetu la klavkombinaj?n por atingi malproksimajn fokusajn spacojn"},{name:"Helpilo pri atingeblo",legend:"Premu ${a11yHelp}"}]}],backspace:"Retropa?o",tab:"Tabo",enter:"Enigi",shift:"Registrumo",ctrl:"Stirklavo",alt:"Alt-klavo",pause:"Pa?zo",capslock:"Majuskla baskulo",escape:"Eskapa klavo",pageUp:"Anta?a Pa?o",
pageDown:"Sekva Pa?o",end:"Fino",home:"Hejmo",leftArrow:"Sago Maldekstren",upArrow:"Sago Supren",rightArrow:"Sago Dekstren",downArrow:"Sago Suben",insert:"Enmeti","delete":"Forigi",leftWindowKey:"Maldekstra Windows-klavo",rightWindowKey:"Dekstra Windows-klavo",selectKey:"Selektklavo",numpad0:"Nombra Klavaro 0",numpad1:"Nombra Klavaro 1",numpad2:"Nombra Klavaro 2",numpad3:"Nombra Klavaro 3",numpad4:"Nombra Klavaro 4",numpad5:"Nombra Klavaro 5",numpad6:"Nombra Klavaro 6",numpad7:"Nombra Klavaro 7",
numpad8:"Nombra Klavaro 8",numpad9:"Nombra Klavaro 9",multiply:"Obligi",add:"Almeti",subtract:"Subtrahi",decimalPoint:"Dekuma Punkto",divide:"Dividi",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Nombra Baskulo",scrollLock:"Ruluma Baskulo",semiColon:"Punktokomo",equalSign:"Egalsigno",comma:"Komo",dash:"Haltostreko",period:"Punkto",forwardSlash:"Oblikvo",graveAccent:"Malakuto",openBracket:"Malferma Krampo",backSlash:"Retroklino",closeBracket:"Ferma Krampo",
singleQuote:"Citilo"});