/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fi",{title:"Saavutettavuus ohjeet",contents:"Ohjeen sis?ll?t. Sulkeaksesi t?m?n dialogin paina ESC.",legend:[{name:"Yleinen",items:[{name:"Editorin ty?kalupalkki",legend:"Paina ${toolbarFocus} siirty?ksesi ty?kalupalkkiin. Siirry seuraavaan ja edelliseen ty?kalupalkin ryhm??n TAB ja SHIFT-TAB n?pp?imill?. Siirry seuraavaan ja edelliseen ty?kalupainikkeeseen k?ytt?m?ll? NUOLI OIKEALLE tai NUOLI VASEMMALLE n?pp?imill?. Paina V?LILY?NTI tai ENTER n?pp?int? aktivoidaksesi ty?kalupainikkeen."},
{name:"Editorin dialogi",legend:"Dialogin sis?ll?, painamalla TAB siirryt seuraavaan dialogin kentt??n, painamalla SHIFT+TAB siirryt aiempaan kentt??n, painamalla ENTER l?het?t dialogin, painamalla ESC peruutat dialogin. Dialogeille joissa on useita v?lilehti?, paina ALT+F10 siirty?ksesi v?lillehtilistaan. Siirty?ksesi seuraavaan v?lilehteen paina TAB tai NUOLI OIKEALLE. Siirry edelliseen v?lilehteen painamalla SHIFT+TAB tai nuoli vasemmalle. Paina V?LILY?NTI tai ENTER valitaksesi v?lilehden."},{name:"Editorin oheisvalikko",
legend:"Paina ${contextMenu} tai SOVELLUSPAINIKETTA avataksesi oheisvalikon. Liiku seuraavaan valikon vaihtoehtoon TAB tai NUOLI ALAS n?pp?imill?. Siirry edelliseen vaihtoehtoon SHIFT+TAB tai NUOLI YL?S n?pp?imill?. Paina V?LILY?NTI tai ENTER valitaksesi valikon kohdan. Avataksesi nykyisen kohdan alivalikon paina V?LILY?NTI tai ENTER tai NUOLI OIKEALLE painiketta. Siirty?ksesi takaisin valikon ylemm?lle tasolle paina ESC tai NUOLI vasemmalle. Oheisvalikko suljetaan ESC painikkeella."},{name:"Editorin listalaatikko",
legend:"Listalaatikon sis?ll? siirry seuraavaan listan kohtaan TAB tai NUOLI ALAS painikkeilla. Siirry edelliseen listan kohtaan SHIFT+TAB tai NUOLI YL?S painikkeilla. Paina V?LILY?NTI tai ENTER valitaksesi listan vaihtoehdon. Paina ESC sulkeaksesi listalaatikon."},{name:"Editorin elementtipolun palkki",legend:"Paina ${elementsPathFocus} siirty?ksesi elementtipolun palkkiin. Siirry seuraavaan elementtipainikkeeseen TAB tai NUOLI OIKEALLE painikkeilla. Siirry aiempaan painikkeeseen SHIFT+TAB tai NUOLI VASEMMALLE painikkeilla. Paina V?LILY?NTI tai ENTER valitaksesi elementin editorissa."}]},
{name:"Komennot",items:[{name:"Peruuta komento",legend:"Paina ${undo}"},{name:"Tee uudelleen komento",legend:"Paina ${redo}"},{name:"Lihavoi komento",legend:"Paina ${bold}"},{name:"Kursivoi komento",legend:"Paina ${italic}"},{name:"Alleviivaa komento",legend:"Paina ${underline}"},{name:"Linkki komento",legend:"Paina ${link}"},{name:"Pienenn? ty?kalupalkki komento",legend:"Paina ${toolbarCollapse}"},{name:"Siirry aiempaan fokustilaan komento",legend:"Paina ${accessPreviousSpace} siiry?ksesi l?himp??n kursorin edell? olevaan saavuttamattomaan fokustilaan, esimerkiksi: kaksi vierekk?ist? HR elementti?. Toista n?pp?inyhdistelm?? p??st?ksesi kauempana oleviin fokustiloihin."},
{name:"Siirry seuraavaan fokustilaan komento",legend:"Paina ${accessPreviousSpace} siiry?ksesi l?himp??n kursorin j?lkeen olevaan saavuttamattomaan fokustilaan, esimerkiksi: kaksi vierekk?ist? HR elementti?. Toista n?pp?inyhdistelm?? p??st?ksesi kauempana oleviin fokustiloihin."},{name:"Saavutettavuus ohjeet",legend:"Paina ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",
end:"End",home:"Home",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numeron?pp?imist? 0",numpad1:"Numeron?pp?imist? 1",numpad2:"Numeron?pp?imist? 2",numpad3:"Numeron?pp?imist? 3",numpad4:"Numeron?pp?imist? 4",numpad5:"Numeron?pp?imist? 5",numpad6:"Numeron?pp?imist? 6",numpad7:"Numeron?pp?imist? 7",numpad8:"Numeron?pp?imist? 8",
numpad9:"Numeron?pp?imist? 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Puolipiste",equalSign:"Equal Sign",comma:"Pilkku",dash:"Dash",period:"Piste",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});