/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","hu",{title:"Kisegít? utasítások",contents:"Súgó tartalmak. A párbeszédablak bezárásához nyomjon ESC-et.",legend:[{name:"általános",items:[{name:"Szerkeszt? Eszk?ztár",legend:"Nyomjon ${toolbarFocus} hogy kijel?lje az eszk?ztárat. A k?vetkez? és el?z? eszk?ztár csoporthoz a TAB és SHIFT TAB-al juthat el. A k?vetkez? és el?z? eszk?ztár gombhoz a BAL NYíL vagy JOBB NYíL gombbal juthat el. Nyomjon SPACE-t vagy ENTER-t hogy aktiválja az eszk?ztár gombot."},{name:"Szerkesz? párbeszéd ablak",
legend:"Párbeszédablakban nyomjon TAB-ot a k?vetkez? párbeszédmez?h?z ugráshoz, nyomjon SHIFT + TAB-ot az el?z? mez?h?z ugráshoz, nyomjon ENTER-t a párbeszédablak elfogadásához, nyomjon ESC-et a párbeszédablak elvetéséhez. Azokhoz a párbeszédablakokhoz, amik t?bb fület tartalmaznak, nyomjon ALT + F10-et hogy a fülekre ugorjon. Ezután a TAB-al vagy a JOBB NYíLLAL a k?vetkez? fülre ugorhat. Az el?z? fülre ugráshoz használja a SHIFT + TAB-ot vagy a BAL NYILAT. Nyomjon SPACE-t vagy ENTER-t hogy kijel?lje a fület."},
{name:"Szerkeszt? helyi menü",legend:"Nyomjon ${contextMenu}-t vagy ALKALMAZáS BILLENTY?T a helyi menü megnyitásához. Ezután a k?vetkez? menüpontra léphet a TAB vagy LEFELé NYíLLAL. Az el?z? opciót a SHIFT+TAB vagy FELFELé NYíLLAL érheti el. Nyomjon SPACE-t vagy ENTER-t a menüpont kiválasztásához. A jelenlegi menüpont almenüjének megnyitásához nyomjon SPACE-t vagy ENTER-t, vagy JOBB NYILAT. A f?menüh?z való visszatéréshez nyomjon ESC-et vagy BAL NYILAT. A helyi menü bezárása az ESC billenty?vel lehetséges."},
{name:"Szerkeszt? lista",legend:"A listán belül a k?vetkez? elemre a TAB vagy LEFELé NYíLLAL mozoghat. Az el?z? elem kiválasztásához nyomjon SHIFT+TAB-ot vagy FELFELé NYILAT. Nyomjon SPACE-t vagy ENTER-t az elem kiválasztásához. Az ESC billenty? megnyomásával bezárhatja a listát."},{name:"Szerkeszt? elem utak sáv",legend:"Nyomj ${elementsPathFocus} hogy kijel?ld a elemek út sávját. A k?vetkez? elem gombhoz a TAB-al vagy a JOBB NYíLLAL juthatsz el. Az el?z? gombhoz a SHIFT+TAB vagy BAL NYíLLAL mehetsz. A SPACE vagy ENTER billenty?vel kiválaszthatod az elemet a szerkeszt?ben."}]},
{name:"Parancsok",items:[{name:"Parancs visszavonása",legend:"Nyomj ${undo}"},{name:"Parancs megismétlése",legend:"Nyomjon ${redo}"},{name:"Félk?vér parancs",legend:"Nyomjon ${bold}"},{name:"D?lt parancs",legend:"Nyomjon ${italic}"},{name:"Aláhúzott parancs",legend:"Nyomjon ${underline}"},{name:"Link parancs",legend:"Nyomjon ${link}"},{name:"Szerkeszt?sáv ?sszecsukása parancs",legend:"Nyomjon ${toolbarCollapse}"},{name:"Hozzáférés az el?z? fókusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzáférj a legk?zelebbi elérhetetlen fókusz helyhez a hiányjel el?tt, például: két szomszédos HR elemhez. Ismételd meg a billenty?kombinációt hogy megtaláld a távolabbi fókusz helyeket."},
{name:"Hozzáférés a k?vetkez? fókusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzáférj a legk?zelebbi elérhetetlen fókusz helyhez a hiányjel után, például: két szomszédos HR elemhez. Ismételd meg a billenty?kombinációt hogy megtaláld a távolabbi fókusz helyeket."},{name:"Kisegít? súgó",legend:"Nyomjon ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",
end:"End",home:"Home",leftArrow:"balra nyíl",upArrow:"felfelé nyíl",rightArrow:"jobbra nyíl",downArrow:"lefelé nyíl",insert:"Insert","delete":"Delete",leftWindowKey:"bal Windows-billenty?",rightWindowKey:"jobb Windows-billenty?",selectKey:"Billenty? választása",numpad0:"Számbillenty?k 0",numpad1:"Számbillenty?k 1",numpad2:"Számbillenty?k 2",numpad3:"Számbillenty?k 3",numpad4:"Számbillenty?k 4",numpad5:"Számbillenty?k 5",numpad6:"Számbillenty?k 6",numpad7:"Számbillenty?k 7",numpad8:"Számbillenty?k 8",
numpad9:"Számbillenty?k 9",multiply:"Szorzás",add:"Hozzáadás",subtract:"Kivonás",decimalPoint:"Tizedespont",divide:"Osztás",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Pontosvessz?",equalSign:"Egyenl?ségjel",comma:"Vessz?",dash:"K?t?jel",period:"Pont",forwardSlash:"Perjel",graveAccent:"Visszafelé d?l? ékezet",openBracket:"Nyitó sz?gletes zárójel",backSlash:"fordított perjel",closeBracket:"Záró sz?gletes zárójel",
singleQuote:"szimpla idéz?jel"});