/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","lv",{title:"Pieejamības instrukcija",contents:"Palīdzības saturs. Lai aizvērtu ciet ?o dialogu nospiediet ESC.",legend:[{name:"Galvenais",items:[{name:"Redaktora rīkjosla",legend:"Nospiediet ${toolbarFocus} lai pārvietotos uz rīkjoslu. Lai pārvietotos uz nāko?o vai iepriek?ējo rīkjoslas grupu izmantojiet pogu TAB un SHIFT+TAB.  Lai pārvietotos uz nāko?o vai iepriek?ējo rīkjoslas pogu izmantojiet Kreiso vai Labo bulti?u. Nospiediet Atstarpi vai ENTER lai aktivizētu rīkjosla pogu."},
{name:"Redaktora dialoga  logs",legend:"Dialoga logā nospiediet pogu TAB lai pārvietotos uz nāko?o dialoga loga lauku, nospiediet SHIFT+TAB lai atgrieztos iepriek?ējā laukā, nospiediet ENTER lai apstiprinātu dialoga datus, nospiediet ESC lai aizvērtu ?o dialogu. Dialogam kuram ir vairākas cilnes, nospiediet ALT+F10 lai pārvietotos uz nepiecie?amo cilni.  Lai pārvietotos uz nāko?o cilni izmantojiet pogu TAB vai Labo bulti?u. Lai pārvietotos uz iepriek?ējo cilni nospiediet SHIFT+TAB vai kreiso bulti?u. Nospiediet SPACE vai ENTER lai izvēlētos lapas cilni."},
{name:"Redaktora satura izvēle",legend:"Nospiediet ${contextMenu} vai APPLICATION KEY lai atvērtu satura izvēlni. Lai pārvietotos uz nāko?o izvēlnes opciju izmantojiet pogu TAB vai pogu Bulti?u uz leju. Lai pārvietotos uz iepriek?ējo opciju izmantojiet  SHIFT+TAB vai pogu Bulti?a uz aug?u. Nospiediet SPACE vai ENTER lai izvelētos izvēlnes opciju. Atveriet teko?ajā opcija apak?izvēlni ar SAPCE vai ENTER ka ari to var izdarīt ar Labo bulti?u. Lai atgrieztos atpaka? uz sakuma izvēlni nospiediet ESC vai Kreiso bulti?u. Lai aizvērtu ciet izvēlnes saturu nospiediet ESC."},
{name:"Redaktora saraksta lauks",legend:"Saraksta laukā, lai pārvietotos uz nāko?o saraksta elementu nospiediet TAB vai pogu Bulti?a uz leju. Lai pārvietotos uz iepriek?ējo saraksta elementu nospiediet SHIFT+TAB vai pogu Bulti?a uz aug?u. Nospiediet SPACE vai ENTER lai izvēlētos saraksta opcijas. Nospiediet ESC lai aizvērtu saraksta lauku. "},{name:"Redaktora elementa ce?a josla",legend:"Nospiediet ${elementsPathFocus} lai pārvietotos uz  elementa ce?a joslu. Lai pārvietotos uz nāko?o elementa pogu izmantojiet TAB vai Labo bulti?u. Lai pārvietotos uz iepriek?ējo elementa pogu  izmantojiet SHIFT + TAB vai Kreiso bulti?u. Nospiediet SPACE vai ENTER lai izvēlētos elementu redaktorā."}]},
{name:"Komandas",items:[{name:"Komanda atcelt darbību",legend:"Nospiediet ${undo}"},{name:"Komanda atkārtot darbību",legend:"Nospiediet ${redo}"},{name:"Treknraksta komanda",legend:"Nospiediet ${bold}"},{name:"Kursīva komanda",legend:"Nospiediet ${italic}"},{name:"Apak?svītras komanda ",legend:"Nospiediet ${underline}"},{name:"Hipersaites komanda",legend:"Nospiediet ${link}"},{name:"Rīkjoslas aizvēr?anas komanda",legend:"Nospiediet ${toolbarCollapse}"},{name:"Piek?ūt iepriek?ējai fokusa vietas komandai",
legend:"Nospiediet ${accessPreviousSpace} lai piek?ūtu tuvākajai nepieejamajai fokusa vietai pirms kursora. Piemēram: diviem blakus eso?iem līnijas HR elementiem. Atkārtojiet tausti?u kombināciju lai piek?ūtu pie tālākām vietām."},{name:"Piek?ūt nāko?ā fokusa apgabala komandai",legend:"Nospiediet ${accessNextSpace} lai piek?ūtu tuvākajai nepieejamajai fokusa vietai pēc kursora. Piemēram: diviem blakus eso?iem līnijas HR elementiem. Atkārtojiet tausti?u kombināciju lai piek?ūtu pie tālākām vietām."},
{name:"Pieejamības palīdzība",legend:"Nospiediet ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",
numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",
graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});