/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","nb",{title:"Instruksjoner for tilgjengelighet",contents:"Innhold for hjelp. Trykk ESC for ? lukke denne dialogen.",legend:[{name:"Generelt",items:[{name:"Verkt?ylinje for editor",legend:"Trykk ${toolbarFocus} for ? navigere til verkt?ylinjen. Flytt til neste og forrige verkt?ylinjegruppe med TAB og SHIFT-TAB. Flytt til neste og forrige verkt?ylinjeknapp med H?YRE PILTAST og VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for ? aktivere verkt?ylinjeknappen."},{name:"Dialog for editor",
legend:"Mens du er i en dialog, trykk TAB for ? navigere til neste dialogfelt, press SHIFT + TAB for ? flytte til forrige felt, trykk ENTER for ? akseptere dialogen, trykk ESC for ? avbryte dialogen. For dialoger med flere faner, trykk ALT + F10 for ? navigere til listen over faner. G? til neste fane med TAB eller H?YRE PILTAST. G? til forrige fane med SHIFT + TAB eller VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for ? velge fanen."},{name:"Kontekstmeny for editor",legend:"Trykk ${contextMenu} eller MENYKNAPP for ? ?pne kontekstmeny. G? til neste alternativ i menyen med TAB eller PILTAST NED. G? til forrige alternativ med SHIFT+TAB eller PILTAST OPP. Trykk MELLOMROM eller ENTER for ? velge menyalternativet. ?pne undermenyen p? valgt alternativ med MELLOMROM eller ENTER eller H?YRE PILTAST. G? tilbake til overordnet menyelement med ESC eller VENSTRE PILTAST. Lukk kontekstmenyen med ESC."},
{name:"Listeboks for editor",legend:"I en listeboks, g? til neste alternativ i listen med TAB eller PILTAST NED. G? til forrige alternativ i listen med SHIFT + TAB eller PILTAST OPP. Trykk MELLOMROM eller ENTER for ? velge alternativet i listen. Trykk ESC for ? lukke listeboksen."},{name:"Verkt?ylinje for elementsti",legend:"Trykk ${elementsPathFocus} for ? navigere til verkt?ylinjen som viser elementsti. G? til neste elementknapp med TAB eller H?YRE PILTAST. G? til forrige elementknapp med SHIFT+TAB eller VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for ? velge elementet i editoren."}]},
{name:"Hurtigtaster",items:[{name:"Angre",legend:"Trykk ${undo}"},{name:"Gj?r om",legend:"Trykk ${redo}"},{name:"Fet tekst",legend:"Trykk ${bold}"},{name:"Kursiv tekst",legend:"Trykk ${italic}"},{name:"Understreking",legend:"Trykk ${underline}"},{name:"Lenke",legend:"Trykk ${link}"},{name:"Skjul verkt?ylinje",legend:"Trykk ${toolbarCollapse}"},{name:"G? til forrige fokusomr?de",legend:"Trykk ${accessPreviousSpace} for ? komme til n?rmeste fokusomr?de f?r skrivemark?ren som ikke kan n?s p? vanlig m?te, for eksempel to tilst?tende HR-elementer. Gjenta tastekombinasjonen for ? komme til fokusomr?der lenger unna i dokumentet."},
{name:"G? til neste fokusomr?de",legend:"Trykk ${accessNextSpace} for ? komme til n?rmeste fokusomr?de etter skrivemark?ren som ikke kan n?s p? vanlig m?te, for eksempel to tilst?tende HR-elementer. Gjenta tastekombinasjonen for ? komme til fokusomr?der lenger unna i dokumentet."},{name:"Hjelp for tilgjengelighet",legend:"Trykk ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tabulator",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",
pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Venstre piltast",upArrow:"Opp-piltast",rightArrow:"H?yre piltast",downArrow:"Ned-piltast",insert:"Insert","delete":"Delete",leftWindowKey:"Venstre Windows-tast",rightWindowKey:"H?yre Windows-tast",selectKey:"Select key",numpad0:"Numerisk tastatur 0",numpad1:"Numerisk tastatur 1",numpad2:"Numerisk tastatur 2",numpad3:"Numerisk tastatur 3",numpad4:"Numerisk tastatur 4",numpad5:"Numerisk tastatur 5",numpad6:"Numerisk tastatur 6",numpad7:"Numerisk tastatur 7",
numpad8:"Numerisk tastatur 8",numpad9:"Numerisk tastatur 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semikolon",equalSign:"Likhetstegn",comma:"Komma",dash:"Bindestrek",period:"Punktum",forwardSlash:"Forover skr?strek",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Bakover skr?strek",
closeBracket:"Close Bracket",singleQuote:"Single Quote"});