/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","pl",{title:"Instrukcje dotycz?ce dost?pno?ci",contents:"Zawarto?? pomocy. Wci?nij ESC, aby zamkn?? to okno.",legend:[{name:"Informacje ogólne",items:[{name:"Pasek narz?dzi edytora",legend:"Wci?nij ${toolbarFocus} aby przej?? do paska narz?dzi. Przejd? do nast?pnej i poprzedniej grupy narz?dzi u?ywaj?c TAB oraz SHIFT-TAB. Przejd? do nast?pnego i poprzedniego narz?dzia u?ywaj?c STRZA?KI W PRAWO lub STRZA?KI W LEWO. Wci?nij SPACJ? lub ENTER, aby aktywowa? zaznaczone narz?dzie."},
{name:"Okno dialogowe edytora",legend:"B?d?c w oknie dialogowym wci?nij TAB aby przej?? do nast?pnego pola dialogowego, wci?nij SHIFT + TAB aby przej?? do poprzedniego pola, wci?nij ENTER aby wys?a? dialog, wci?nij ESC aby anulowa? dialog. Dla okien dialogowych z wieloma zak?adkami, wci?nij ALT + F10 aby przej?? do listy zak?adek. Gdy to zrobisz przejd? do nast?pnej zak?adki wciskaj?c TAB lub STRZA?K? W PRAWO. Przejd? do poprzedniej zak?adki wciskaj?c SHIFT + TAB lub STRZA?K? W LEWO. Wci?nij SPACJ? lub ENTER aby wybra? zak?adk?."},
{name:"Menu kontekstowe edytora",legend:"Wci?nij ${contextMenu} lub PRZYCISK APLIKACJI aby otworzy? menu kontekstowe. Przejd? do nast?pnej pozycji menu wciskaj?c TAB lub STRZA?K? W Dó?. Przejd? do poprzedniej pozycji menu wciskaj?c SHIFT + TAB lub STRZA?K? W GóR?. Wci?nij SPACJ? lub ENTER aby wygra? pozycj? menu. Otwórz pod-menu obecnej pozycji wciskaj?c SPACJ? lub ENTER lub STRZA?K? W PRAWO. Wró? do pozycji nadrz?dnego menu wciskaj?c ESC lub STRZA?K? W LEWO. Zamknij menu wciskaj?c ESC."},{name:"Lista w edytorze",
legend:"W polu listy mo?esz przechodzi? do nast?pnego elementu za pomoc? klawisza TAB lub STRZA?KI W Dó?. Poprzedni element osi?gniesz za pomoc? SHIFT+TAB lub STRZA?KI W GóR?. Za pomoc? SPACJI lub ENTERA wybierzesz dan? opcj? z listy, a za pomoc? klawisza ESC opu?cisz list?."},{name:"Pasek ?cie?ki elementów edytora",legend:"Naci?nij ${elementsPathFocus} w celu przej?cia do paska ?cie?ki elementów edytora. W celu przej?cia do kolejnego elementu naci?nij klawisz Tab lub Strza?ki w prawo. W celu przej?cia do poprzedniego elementu naci?nij klawisze Shift+Tab lub Strza?ki w lewo. By wybra? element w edytorze, u?yj klawisza Spacji lub Enter."}]},
{name:"Polecenia",items:[{name:"Polecenie Cofnij",legend:"Naci?nij ${undo}"},{name:"Polecenie Ponów",legend:"Naci?nij ${redo}"},{name:"Polecenie Pogrubienie",legend:"Naci?nij ${bold}"},{name:"Polecenie Kursywa",legend:"Naci?nij ${italic}"},{name:"Polecenie Podkre?lenie",legend:"Naci?nij ${underline}"},{name:"Polecenie Wstaw/ edytuj odno?nik",legend:"Naci?nij ${link}"},{name:"Polecenie schowaj pasek narz?dzi",legend:"Naci?nij ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:"Pomoc dotycz?ca dost?pno?ci",legend:"Naci?nij ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Strza?ka w lewo",
upArrow:"Strza?ka w gór?",rightArrow:"Strza?ka w prawo",downArrow:"Strza?ka w dó?",insert:"Insert","delete":"Delete",leftWindowKey:"Lewy klawisz Windows",rightWindowKey:"Prawy klawisz Windows",selectKey:"Klawisz wyboru",numpad0:"Klawisz 0 na klawiaturze numerycznej",numpad1:"Klawisz 1 na klawiaturze numerycznej",numpad2:"Klawisz 2 na klawiaturze numerycznej",numpad3:"Klawisz 3 na klawiaturze numerycznej",numpad4:"Klawisz 4 na klawiaturze numerycznej",numpad5:"Klawisz 5 na klawiaturze numerycznej",
numpad6:"Klawisz 6 na klawiaturze numerycznej",numpad7:"Klawisz 7 na klawiaturze numerycznej",numpad8:"Klawisz 8 na klawiaturze numerycznej",numpad9:"Klawisz 9 na klawiaturze numerycznej",multiply:"Przemnó?",add:"Plus",subtract:"Minus",decimalPoint:"Separator dziesi?tny",divide:"Podziel",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"?rednik",equalSign:"Znak równo?ci",comma:"Przecinek",dash:"Pauza",
period:"Kropka",forwardSlash:"Uko?nik prawy",graveAccent:"Akcent s?aby",openBracket:"Nawias kwadratowy otwieraj?cy",backSlash:"Uko?nik lewy",closeBracket:"Nawias kwadratowy zamykaj?cy",singleQuote:"Apostrof"});