/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","ro",{title:"Instruc?iuni de accesibilitate",contents:"Cuprins. Pentru a ?nchide acest dialog, ap?sa?i tasta ESC.",legend:[{name:"General",items:[{name:"Editeaz? bara instrumente.",legend:"Apas? ${toolbarFocus} pentru a naviga prin bara de instrumente. Pentru a te mi?ca prin grupurile de instrumente folose?te tastele TAB ?i SHIFT-TAB. Pentru a te mi?ca intre diverse instrumente folose?te tastele S?GEAT? DREAPTA sau S?GEAT? ST?NGA. Apas? butonul SPA?IU sau ENTER pentru activarea instrumentului."},
{name:"Dialog editor",legend:"?ntr-un dialog, apas? TAB pentru a naviga spre campul urm?tor de dialog, apas? SHIFT + TAB pentru a te duce la campul anterior, apas? ENTER pentru a trimite dialogul, apas? ESC pentru a anula dialogul. Pentru dialoguri care au mai multe subferestre, apas? ALT + F10 pentr a naviga ?n lista de subferestre. Treci la subferestrea urm?toare cu TAB sau S?GEAT? DREAPTA. Treci la subfereastra anterioar? cu SHIFT + TAB sau S?GEAT? ST?NGA. Apas? SPA?IU sau ENTER pentru a selecta subfereastra."},
{name:"Editor meniu contextual",legend:"Apas? ${contextMenu} sau TASTA MENIU pentru a deschide meniul contextual. Treci la urm?toarea op?iune din meniu cu TAB sau S?GEAT? JOS. Treci la op?iunea anterioar? cu  SHIFT+TAB sau S?GEAT? SUS. Apas? SPA?IU sau ENTER pentru a selecta op?iunea din meniu. Deschide sub-meniul op?iunii curente cu SPA?IU sau ENTER sau S?GEAT? DREAPTA. Revino la elementul din meniul p?rinte cu ESC sau S?GEAT? ST?NGA. ?nchide meniul de context cu ESC."},{name:"Editor Caset? List?",
legend:"?n interiorul unei liste, treci la urm?torull element cu TAB sau S?GEAT? JOS. Treci la elementul anterior din list? cu SHIFT + TAB sau S?GEAT? SUS. Apas? SPA?IU sau ENTER pentru a selecta op?iunea din list?. Apas? ESC pentru a ?nchide lista."},{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with  SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},
{name:"Comenzi",items:[{name:" Undo command",legend:"Apas? ${undo}"},{name:"Comanda precedent?",legend:"Apas? ${redo}"},{name:"Comanda ?ngro?at",legend:"Apas? ${bold}"},{name:"Comanda Inclinat",legend:"Apas? ${italic}"},{name:"Comanda Subliniere",legend:"Apas? ${underline}"},{name:"Comanda Legatur?",legend:"Apas? ${link}"},{name:" Toolbar Collapse command",legend:"Press ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Accessibility Help",legend:"Press ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Left Arrow",
upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",
f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});