/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sk",{title:"In?trukcie prístupnosti",contents:"Pomocny obsah. Pre zatvorenie tohto okna, stla?te ESC.",legend:[{name:"V?eobecne",items:[{name:"Li?ta nástrojov editora",legend:"Stla?te ${toolbarFocus} pre navigáciu na li?tu nástrojov. Medzi ?al?ou a predchádzajúcou li?tou nástrojov sa pohybujete s TAB a SHIFT-TAB. Medzi ?al?ím a predchádzajúcim tla?idlom na li?te nástrojov sa pohybujete s pravou ?ípkou a ?avou ?ípkou. Stla?te medzerník alebo ENTER pre aktiváciu tla?idla li?ty nástrojov."},
{name:"Editorovy dialóg",legend:"V dialogu, stla?te TAB pre navigáciu na ?al?ie dialógové pole, stla?te STIFT + TAB pre presun na predchádzajúce pole, stla?te ENTER pre odoslanie dialógu, stla?te ESC pre zru?enie dialógu. Pre dialógy, ktoré majú viac zálo?iek, stla?te ALT + F10 pre navigácou do zoznamu zálo?iek. Potom sa posúvajte k ?al?ej ?álo?ke pomocou TAB alebo pravou ?ípkou. Pre presun k predchádzajúcej zálo?ke, stla?te SHIFT + TAB alebo ?avú ?ípku. Stla?te medzerník alebo ENTER pre vybranie zálo?ky."},
{name:"Editorové kontextové menu",legend:"Stla?te ${contextMenu} alebo APPLICATION KEY pre otvorenie kontextového menu. Potom sa presúvajte na ?al?ie mo?nosti menu s TAB alebo dolnou ?ípkou. Presunte sa k predchádzajúcej mo?nosti s SHIFT + TAB alebo hornou ?ípkou. Stla?te medzerník alebo ENTER pre vyber mo?nosti menu. Otvorte pod-menu danej mo?nosti s medzerníkom, alebo ENTER, alebo pravou ?ípkou. Vrá?te sa sp?? do polo?ky rodi?ovského menu s ESC alebo ?avou ?ípkou. Zatvorte kontextové menu s ESC."},
{name:"Editorov box zoznamu",legend:"V boxe zoznamu, presuňte sa na ?al?iu polo?ku v zozname s TAB alebo dolnou ?ípkou. Presuňte sa k predchádzajúcej polo?ke v zozname so SHIFT + TAB alebo hornou ?ípkou. Stla?te medzerník alebo ENTER pre vyber mo?nosti zoznamu. Stla?te ESC pre zatvorenie boxu zoznamu."},{name:"Editorove pásmo cesty prvku",legend:"Stla?te ${elementsPathFocus} pre navigovanie na pásmo cesty elementu. Presuňte sa na tla?idlo ?al?ieho prvku s TAB alebo pravou ?ípkou. Presuňte sa k predchádzajúcemu tla?idlu s SHIFT + TAB alebo ?avou ?ípkou. Stla?te medzerník alebo ENTER pre vyber prvku v editore."}]},
{name:"Príkazy",items:[{name:"Vráti? príkazy",legend:"Stla?te ${undo}"},{name:"Nanovo vráti? príkaz",legend:"Stla?te ${redo}"},{name:"Príkaz na stu?nenie",legend:"Stla?te ${bold}"},{name:"Príkaz na kurzívu",legend:"Stla?te ${italic}"},{name:"Príkaz na pod?iarknutie",legend:"Stla?te ${underline}"},{name:"Príkaz na odkaz",legend:"Stla?te ${link}"},{name:"Príkaz na zbalenie li?ty nástrojov",legend:"Stla?te ${toolbarCollapse}"},{name:"Prejs? na predchádzajúcu zamerate?nú medzeru príkazu",legend:"Stla?te ${accessPreviousSpace} pre prístup na najbli??ie nedosiahnute?né zamerate?né medzery pred vsuvkuo. Napríklad: dve za sebou idúce horizontálne ?iary. Opakujte kombináciu klávesov pre dosiahnutie vzdialenych zamerate?nych medzier."},
{name:"Prejs? na ?al?í ",legend:"Stla?te ${accessNextSpace} pre prístup na najbli??ie nedosiahnute?né zamerate?né medzery po vsuvke. Napríklad: dve za sebou idúce horizontálne ?iary. Opakujte kombináciu klávesov pre dosiahnutie vzdialenych zamerate?nych medzier."},{name:"Pomoc prístupnosti",legend:"Stla?te ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Stránka hore",pageDown:"Stránka dole",
end:"End",home:"Home",leftArrow:"?ípka na?avo",upArrow:"?ípka hore",rightArrow:"?ípka napravo",downArrow:"?ípka dole",insert:"Insert","delete":"Delete",leftWindowKey:"?avé Windows tla?idlo",rightWindowKey:"Pravé Windows tla?idlo",selectKey:"Tla?idlo Select",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Násobenie",add:"S?ítanie",subtract:"Od?ítanie",
decimalPoint:"Desatinná ?iarka",divide:"Delenie",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Bodko?iarka",equalSign:"Rovná sa",comma:"?iarka",dash:"Pom??ka",period:"Bodka",forwardSlash:"Lomítko",graveAccent:"Zd?razňovanie prízvuku",openBracket:"Hranatá zátvorka otváracia",backSlash:"Backslash",closeBracket:"Hranatá zátvorka zatváracia",singleQuote:"Jednoduché úvodzovky"});