/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sl",{title:"Navodila Dostopnosti",contents:"Vsebina Pomo?i. ?e ?elite zapreti to pogovorno okno pritisnite ESC.",legend:[{name:"Splo?no",items:[{name:"Urejevalna Orodna Vrstica",legend:"Pritisnite ${toolbarFocus} za pomik v orodno vrstico. Z TAB in SHIFT-TAB se pomikate na naslednjo in prej?njo skupino orodne vrstice. Z DESNO PU??ICO ali LEVO PU??ICO se pomikate na naslednji in prej?nji gumb orodne vrstice. Pritisnite SPACE ali ENTER, da aktivirate gumb orodne vrstice."},
{name:"Urejevalno Pogovorno Okno",legend:"Znotraj pogovornega okna, pritisnite tipko TAB za pomik na naslednjo pogovorno polje, pritisnite SHIFT + TAB za pomik v prej?nje polje, pritisnite tipko ENTER za predlo?itev pogovornega okna, pritisnite tipko ESC, da prekli?ete okno. Za okna, ki imajo ve? zavihkov, pritisnite ALT + F10, da pojdete na seznam zavihkov. Na naslednji zavihek se premaknete s tipko TAB ali DESNO PU??ICO. Z SHIFT + TAB ali LEVO PU??ICO pa se premaknete na prej?nji zavihek. Pritisnite tipko SPACE ali ENTER za izbiro zavihka."},
{name:"Urejevalni Kontekstni Meni",legend:"Pritisnite ${contextMenu} ali APPLICATION KEY, da odprete kontekstni meni. Nato se premaknite na naslednjo mo?nost menija s tipko TAB ali PU??ICA DOL. Premakniti se na prej?njo mo?nost z SHIFT + TAB ali PU??ICA GOR. Pritisnite SPACE ali ENTER za izbiro mo?nosti menija. Odprite podmeni trenutne mo?nosti menija s tipko SPACE ali ENTER ali DESNA PU??ICA. Vrnite se na mati?ni element menija s tipko ESC ali LEVA PU??ICA. Zaprite kontekstni meni z ESC."},{name:"Urejevalno Seznamsko Polje",
legend:"Znotraj seznama, se premaknete na naslednji element seznama s tipko TAB ali PU??ICO DOL. Z SHIFT + TAB ali PU??ICO GOR se premaknete na prej?nji element seznama. Pritisnite tipko SPACE ali ENTER za izbiro elementa. Pritisnite tipko ESC, da zaprete seznam."},{name:"Urejevalna vrstica poti elementa",legend:"Pritisnite ${elementsPathFocus} za pomikanje po vrstici elementnih poti. S TAB ali DESNA PU??ICA se premaknete na naslednji gumb elementa. Z SHIFT + TAB ali LEVO PU??ICO se premaknete na prej?nji gumb elementa. Pritisnite SPACE ali ENTER za izbiro elementa v urejevalniku."}]},
{name:"Ukazi",items:[{name:"Razveljavi ukaz",legend:"Pritisnite ${undo}"},{name:"Ponovi ukaz",legend:"Pritisnite ${redo}"},{name:"Krepki ukaz",legend:"Pritisnite ${bold}"},{name:"Le?e?i ukaz",legend:"Pritisnite ${italic}"},{name:"Poudarni ukaz",legend:"Pritisnite ${underline}"},{name:"Ukaz povezave",legend:"Pritisnite ${link}"},{name:"Skr?i Orodno Vrstico Ukaz",legend:"Pritisnite ${toolbarCollapse}"},{name:"Dostop do prej?njega ukaza ostrenja",legend:"Pritisnite ${accessPreviousSpace} za dostop do najbli?jega nedosegljivega osredoto?enega prostora pred stre?ico, npr.: dva sosednja HR elementa. Ponovite kombinacijo tipk, da dose?ete oddaljene osredoto?ene prostore."},
{name:"Dostop do naslednjega ukaza ostrenja",legend:"Pritisnite ${accessNextSpace} za dostop do najbli?jega nedosegljivega osredoto?enega prostora po stre?ici, npr.: dva sosednja HR elementa. Ponovite kombinacijo tipk, da dose?ete oddaljene osredoto?ene prostore."},{name:"Pomo? Dostopnosti",legend:"Pritisnite ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",
home:"Home",leftArrow:"Levo pu??ica",upArrow:"Gor pu??ica",rightArrow:"Desno pu??ica",downArrow:"Dol pu??ica",insert:"Insert","delete":"Delete",leftWindowKey:"Leva Windows tipka",rightWindowKey:"Desna Windows tipka",selectKey:"Select tipka",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Zmno?i",add:"Dodaj",subtract:"Od?tej",decimalPoint:"Decimalna vejica",
divide:"Deli",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Podpi?je",equalSign:"ena?aj",comma:"Vejica",dash:"Vezaj",period:"Pika",forwardSlash:"Desna po?evnica",graveAccent:"Krativec",openBracket:"Oklepaj",backSlash:"Leva po?evnica",closeBracket:"Oklepaj",singleQuote:"Opu??aj"});