/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sv",{title:"Hj?lpmedelsinstruktioner",contents:"Hj?lpinneh?ll. F?r att st?nga denna dialogruta trycker du p? ESC.",legend:[{name:"Allm?nt",items:[{name:"Editor verktygsf?lt",legend:"Tryck p? ${toolbarFocus} f?r att navigera till verktygsf?ltet. Flytta till n?sta och f?reg?ende verktygsf?ltsgrupp med TAB och SHIFT-TAB. Flytta till n?sta och f?reg?ende knapp i verktygsf?ltet med H?GERPIL eller V?NSTERPIL. Tryck Space eller ENTER f?r att aktivera knappen i verktygsf?ltet."},
{name:"Dialogeditor",legend:"Inuti en dialogruta, tryck TAB f?r att navigera till n?sta f?lt i dialogrutan. Du trycker SKIFT + TAB f?r att flytta till f?reg?ende f?lt. Tryck ENTER f?r att skicka. Du avbryter och st?nger dialogen med ESC. F?r dialogrutor som har flera flikar, tryck ALT + F10 navigera till fliklistan. Flytta sedan till n?sta flik med H?GERPIL. Flytta till f?reg?ende flik med SHIFT + TAB eller V?NSTERPIL. Tryck Space eller ENTER f?r att v?lja fliken."},{name:"Editor f?r inneh?llsmeny",
legend:"Tryck p? $ {contextMenu} eller PROGRAMTANGENTEN f?r att ?ppna snabbmenyn. Flytta sedan till n?sta menyalternativ med TAB eller NEDPIL. Flytta till f?reg?ende alternativ med SHIFT + TABB eller UPPIL. Tryck Space eller ENTER f?r att v?lja menyalternativ. ?ppna undermeny av nuvarande alternativ med SPACE eller ENTER eller H?GERPIL. G? tillbaka till ?verordnade menyalternativ med ESC eller V?NSTERPIL. St?ng snabbmenyn med ESC."},{name:"Editor f?r List Box",legend:"Inuti en list-box, g? till n?sta listobjekt med TAB eller NEDPIL. Flytta till f?reg?ende listobjekt med SHIFT + TAB eller UPPIL. Tryck Space eller ENTER f?r att v?lja listan alternativet. Tryck ESC f?r att st?nga listan-boxen."},
{name:"Editor f?r elementens s?kv?g",legend:"Tryck p? $ {elementsPathFocus} f?r att navigera till verktygsf?ltet f?r elementens s?kv?gar. Flytta till n?sta elementknapp med TAB eller H?GERPIL. Flytta till f?reg?ende knapp med SKIFT + TAB eller V?NSTERPIL. Tryck Space eller ENTER f?r att v?lja element i redigeraren."}]},{name:"Kommandon",items:[{name:"Kommandot ?ngra",legend:"Tryck p? ${undo}"},{name:"Kommandot g?r om",legend:"Tryck p? ${redo}"},{name:"Kommandot fet stil",legend:"Tryck p? ${bold}"},
{name:"Kommandot kursiv",legend:"Tryck p? ${italic}"},{name:"Kommandot understruken",legend:"Tryck p? ${underline}"},{name:"Kommandot l?nk",legend:"Tryck p? ${link}"},{name:"Verktygsf?lt D?lj kommandot",legend:"Tryck p? ${toolbarCollapse}"},{name:"G? till f?reg?ende fokus plats",legend:"Tryck p? ${accessPreviousSpace} f?r att g? till n?rmast on?bara utrymme f?re mark?ren, exempel: tv? intilliggande HR element. Repetera tangentkombinationen f?r att g? till n?sta."},{name:"Tillg? n?sta fokuskommandots utrymme",
legend:"Tryck ${accessNextSpace} p? f?r att komma ?t den n?rmaste on?bar fokus utrymme efter cirkumflex, till exempel: tv? intilliggande HR element. Upprepa tangentkombinationen f?r att n? avl?gsna fokus utrymmen."},{name:"Hj?lp om tillg?nglighet",legend:"Tryck ${a11yHelp}"}]}],backspace:"Backsteg",tab:"Tab",enter:"Retur",shift:"Skift",ctrl:"Ctrl",alt:"Alt",pause:"Paus",capslock:"Caps lock",escape:"Escape",pageUp:"Sida Up",pageDown:"Sida Ned",end:"Slut",home:"Hem",leftArrow:"V?nsterpil",upArrow:"Uppil",
rightArrow:"H?gerpil",downArrow:"Ned?tpil",insert:"Infoga","delete":"Radera",leftWindowKey:"V?nster Windowstangent",rightWindowKey:"H?ger Windowstangent",selectKey:"V?lj tangent",numpad0:"Nummer 0",numpad1:"Nummer 1",numpad2:"Nummer 2",numpad3:"Nummer 3",numpad4:"Nummer 4",numpad5:"Nummer 5",numpad6:"Nummer 6",numpad7:"Nummer 7",numpad8:"Nummer 8",numpad9:"Nummer 9",multiply:"Multiplicera",add:"Addera",subtract:"Minus",decimalPoint:"Decimalpunkt",divide:"Dividera",f1:"F1",f2:"F2",f3:"F3",f4:"F4",
f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semikolon",equalSign:"Lika med tecken",comma:"Komma",dash:"Minus",period:"Punkt",forwardSlash:"Snedstreck fram?t",graveAccent:"Accent",openBracket:"?ppningsparentes",backSlash:"Snedstreck bak?t",closeBracket:"Slutparentes",singleQuote:"Enkelt Citattecken"});