/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","tr",{title:"Eri?ilebilirlik Talimatlar?",contents:"Yard?m i?eri?i. Bu pencereyi kapatmak i?in ESC tu?una bas?n.",legend:[{name:"Genel",items:[{name:"Düzenleyici Ara? ?ubu?u",legend:"Ara? ?ubu?unda gezinmek i?in ${toolbarFocus} bas?n. TAB ve SHIFT-TAB ile ?nceki ve sonraki ara? ?ubu?u grubuna ta??y?n. SA? OK veya SOL OK ile ?nceki ve sonraki bir ara? ?ubu?u dü?mesini hareket ettirin. SPACE tu?una bas?n veya ara? ?ubu?u dü?mesini etkinle?tirmek i?in ENTER tu?na bas?n."},
{name:"Diyalog Düzenleyici",legend:"Dialog penceresi i?inde, sonraki ileti?im alan?na gitmek i?in SEKME tu?una bas?n, ?nceki alana ge?mek i?in SHIFT + TAB tu?una bas?n, pencereyi g?ndermek i?in ENTER tu?una bas?n, dialog penceresini iptal etmek i?in ESC tu?una bas?n. Birden ?ok sekme sayfalar? olan diyaloglar?n, sekme listesine gitmek i?in ALT + F10 tu?lar?na bas?n. Sonra TAB veya SA? OK sonraki sekmeye ta??y?n. SHIFT + TAB veya SOL OK ile ?nceki sekmeye ge?in. Sekme sayfay? se?mek i?in SPACE veya ENTER tu?una bas?n."},
{name:"??erik Menü Edit?rü",legend:"??erik menüsünü a?mak i?in ${contextMenu} veya UYGULAMA TU?U'na bas?n. Daha sonra SEKME veya A?A?I OK ile bir sonraki menü se?ene?i ta??y?n. SHIFT + TAB veya YUKARI OK ile ?nceki se?ene?e gider. Menü se?ene?ini se?mek i?in SPACE veya ENTER tu?una bas?n. Se?ili se?ene?in alt menüsünü SPACE ya da ENTER veya SA? OK a??n. üst menü ??esini ge?mek i?in ESC veya SOL OK ile geri d?nün. ESC ile ba?lam menüsünü kapat?n."},{name:"Liste Kutusu Edit?rü",legend:"Liste kutusu i?inde, bir sonraki liste ??esine SEKME VEYA A?A?I OK ile ta??y?n. SHIFT + TAB veya YUKARI ?nceki liste ??esi ta??y?n. Liste se?ene?i se?mek i?in SPACE veya ENTER tu?una bas?n. Liste kutusunu kapatmak i?in ESC tu?una bas?n."},
{name:"Element Yol ?ubu?u Edit?rü",legend:"Elementlerin yol ?ubu?unda gezinmek i?in ${ElementsPathFocus} bas?n. SEKME veya SA? OK ile sonraki element dü?mesine ta??y?n. SHIFT + TAB veya SOL OK ?nceki dü?meye hareket ettirin. Edit?r i?indeki elementi se?mek i?in ENTER veya SPACE tu?una bas?n."}]},{name:"Komutlar",items:[{name:"Komutu geri al",legend:"$(undo)'ya bas?n"},{name:"Komutu geri al",legend:"${redo} bas?n"},{name:" Kal?n komut",legend:"${bold} bas?n"},{name:" ?talik komutu",legend:"${italic} bas?n"},
{name:" Alttan ?izgi komutu",legend:"${underline} bas?n"},{name:" Ba?lant? komutu",legend:"${link} bas?n"},{name:" Ara? ?ubu?u Toplama komutu",legend:"${toolbarCollapse} bas?n"},{name:"?nceki komut alan?na odaklan",legend:"Düzeltme imle?inden ?nce, en yak?n uzaktaki alana eri?mek i?in ${accessPreviousSpace} bas?n, ?rne?in: iki birle?ik HR elementleri. Ayn? tu? kombinasyonu tekrar?yla di?er alanlarada ula??n."},{name:"Sonraki komut alan?na odaklan",legend:"Düzeltme imle?inden sonra, en yak?n uzaktaki alana eri?mek i?in ${accessNextSpace} bas?n, ?rne?in: iki birle?ik HR elementleri. Ayn? tu? kombinasyonu tekrar?yla di?er alanlarada ula??n."},
{name:"Eri?ilebilirlik Yard?m?",legend:"${a11yHelp}'e bas?n"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Sayfa Yukar?",pageDown:"Sayfa A?a??",end:"End",home:"Home",leftArrow:"Sol ok",upArrow:"Yukar? ok",rightArrow:"Sa? ok",downArrow:"A?a?? ok",insert:"Insert","delete":"Silme",leftWindowKey:"Sol windows tu?u",rightWindowKey:"Sa? windows tu?u",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",
numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"?arpma",add:"Toplama",subtract:"??karma",decimalPoint:"Ondal?k i?areti",divide:"B?lme",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Noktal? virgül",equalSign:"E?ittir",comma:"Virgül",dash:"Eksi",period:"Nokta",forwardSlash:"Forward Slash",
graveAccent:"Grave Accent",openBracket:"Parantez a?",backSlash:"Backslash",closeBracket:"Parantez kapa",singleQuote:"Tek t?rnak"});