document.writeln('<table width=\"98%\" border=\"0\" align=\"center\">')
document.writeln('<form id=\"SearchForm\" onsubmit=\"return false\" name=\"SearchForm\" method=\"get\" action=\"/item/index.asp\">')
document.writeln('  <tr>')
document.writeln('    <td align=\"center\"><select name=\"t\" id=\"m_t\">')
document.writeln('          <option value=\"1\">名 称</option>')
document.writeln('          <option value=\"2\">简 介</option>')
document.writeln('          <option value=\"3\">开发商</option>')
document.writeln('          <option value=\"4\">录入者</option>')
document.writeln('          <option value=\"5\">关键字</option>')
document.writeln('      </select>')
document.writeln('        <select name=\"tid\" id=\"m_tid\" style=\"width:150px\">')
document.writeln('          <option value=\"0\" selected=\"selected\">所有栏目</option>')
document.writeln('<option value=\'719\'>下载频道 </option><option value=\'719:720\'>──硬件工具 </option><option value=\'719:722\'>──安全相关 </option><option value=\'719:723\'>──多媒体类 </option><option value=\'719:724\'>──图形图像 </option><option value=\'719:725\'>──系统工具 </option><option value=\'719:726\'>──应用软件 </option><option value=\'719:727\'>──网络软件 </option><option value=\'719:728\'>──服务器类 </option><option value=\'719:730\'>──其它源码 </option><option value=\'719:731\'>──PHP源码 </option><option value=\'719:732\'>──.net源码 </option><option value=\'719:733\'>──Asp源码 </option><option value=\'719:1677\'>──听歌软件 </option>        </select>')
document.writeln('        <input name=\"key\" type=\"text\" id=\"m_key\" class=\"textbox\"  value=\"关键字\" onfocus=\"this.select();\"/>')
document.writeln('        <input name=\"ChannelID\" id=\"m_id\" value=\"3\" type=\"hidden\" />')
document.writeln('        <input type=\"button\" onclick=\"turnsearch()\" class=\"inputButton\" name=\"sbtn\" value=\"搜 索\" /></td>')
document.writeln('  </tr>')
document.writeln('</form>')
document.writeln('</table>')
function turnsearch(){location.href='/item/index.asp?c-'+$('#m_id').val()+',tid-'+$('#m_tid').val()+',t-'+$('#m_t').val()+',key-'+$('#m_key').val()+'.html';}
$(document).ready(function() { $(document).keydown(function(e) { if (e.keyCode==13){ turnsearch();} }); });
