document.writeln('<table width=\"98%\" border=\"0\" align=\"center\">')
document.writeln('<form id=\"SearchForm\" onsubmit=\"return false\" name=\"SearchForm\" method=\"get\" action=\"/item/index.asp\">')
document.writeln('  <tr>')
document.writeln('    <td align=\"center\"><select name=\"t\" id=\"m_t\">')
document.writeln('          <option value=\"1\">名 称</option>')
document.writeln('          <option value=\"2\">简 介</option>')
document.writeln('          <option value=\"3\">作 者</option>')
document.writeln('          <option value=\"4\">录入者</option>')
document.writeln('          <option value=\"5\">关键字</option>')
document.writeln('      </select>')
document.writeln('        <select name=\"tid\" id=\"m_tid\" style=\"width:150px\">')
document.writeln('          <option value=\"0\" selected=\"selected\">所有栏目</option>')
document.writeln('<option value=\'694\'>图片频道 </option><option value=\'694:1162\'>──旅游景点 </option><option value=\'694:1163\'>──美女图片 </option><option value=\'694:1165\'>──概念家居 </option><option value=\'694:1203\'>──自然风景 </option><option value=\'694:1204\'>──萌宠大全 </option><option value=\'694:1205\'>──美食每刻 </option><option value=\'694:1206\'>──影视壁纸 </option><option value=\'735:1208\'>──动漫图库 </option>        </select>')
document.writeln('        <input name=\"key\" type=\"text\" id=\"m_key\" class=\"textbox\"  value=\"关键字\" onfocus=\"this.select();\"/>')
document.writeln('        <input name=\"ChannelID\" id=\"m_id\" value=\"2\" type=\"hidden\" />')
document.writeln('        <input type=\"button\" onclick=\"turnsearch()\" class=\"inputButton\" name=\"sbtn\" value=\"搜 索\" /></td>')
document.writeln('  </tr>')
document.writeln('</form>')
document.writeln('</table>')
function turnsearch(){location.href='/item/index.asp?c-'+$('#m_id').val()+',tid-'+$('#m_tid').val()+',t-'+$('#m_t').val()+',key-'+$('#m_key').val()+'.html';}
$(document).ready(function() { $(document).keydown(function(e) { if (e.keyCode==13){ turnsearch();} }); });
